MEALS = [
    {
        "name": "Kuru Fasulye",
        "desc": "Salçalı, tereyağlı klasik kuru fasulye; yanına pilav yakışır.",
        "region": "turkiye", "categories": ["baklagil"],
        "prep": 15, "cook": 70, "servings": 4, "cost": 150,
        "nutrition": (320, 18, 48, 6, 14),
        "ingredients": [("Kuru fasulye", 300), ("Soğan", 1), ("Salça", 1), ("Biber salçası", 1), ("Tereyağı", 1), ("Tuz", 1), ("Pul biber", 0.5)],
        "recipe": "1. Fasulyeyi akşamdan ıslatın, sabah suyunu değiştirip 30 dakika haşlayın ve suyunu süzün.\n2. Tereyağında ince doğranmış soğanı kavurun, salçaları ekleyip kokusu çıkana kadar pişirin.\n3. Fasulyeyi ekleyin, üzerini geçecek kadar sıcak su koyup kısık ateşte 40 dakika pişirin.\n4. Tuzu en son ekleyin.\n5. Pilav ve turşuyla servis edin.",
    },
    {
        "name": "Etli Kuru Fasulye",
        "desc": "Kuşbaşı etle pişen, daha doyurucu kuru fasulye.",
        "region": "turkiye", "categories": ["baklagil", "et"],
        "prep": 20, "cook": 90, "servings": 4, "cost": 330,
        "nutrition": (430, 30, 45, 14, 13),
        "ingredients": [("Kuru fasulye", 300), ("Kuşbaşı et", 250), ("Soğan", 1), ("Salça", 1), ("Tereyağı", 1), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Fasulyeyi bir gece ıslatıp haşlayın, suyunu süzün.\n2. Kuşbaşı eti tereyağında suyunu çekene kadar kavurun, soğanı ve salçayı ekleyin.\n3. Fasulyeyi ekleyip üzerini geçecek kadar sıcak su koyun.\n4. Kısık ateşte et ve fasulye yumuşayana kadar yaklaşık 1 saat pişirin.\n5. Tuz ve karabiberle tatlandırıp servis edin.",
    },
    {
        "name": "Nohut Yemeği",
        "desc": "Zeytinyağlı, salçalı, sade nohut yemeği.",
        "region": "turkiye", "categories": ["baklagil"],
        "prep": 15, "cook": 60, "servings": 4, "cost": 130,
        "nutrition": (300, 15, 45, 7, 12),
        "ingredients": [("Nohut", 300), ("Soğan", 1), ("Salça", 1), ("Zeytinyağı", 2), ("Tuz", 1)],
        "recipe": "1. Nohutu bir gece bol suda ıslatın.\n2. Yağda soğanı kavurup salçayı ekleyin.\n3. Süzdüğünüz nohutu ilave edip üzerini geçecek kadar su koyun.\n4. Kısık ateşte nohut yumuşayana kadar yaklaşık 50 dakika pişirin, tuzunu ekleyin.",
    },
    {
        "name": "Etli Nohut Yemeği",
        "desc": "Kuşbaşı etli, domatesli nohut yemeği.",
        "region": "ic-anadolu", "categories": ["baklagil", "et"],
        "prep": 20, "cook": 75, "servings": 4, "cost": 320,
        "nutrition": (410, 30, 38, 15, 10),
        "ingredients": [("Nohut", 250), ("Kuşbaşı et", 250), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Nohutu bir gece ıslatıp yarı yumuşayana kadar haşlayın.\n2. Tereyağında eti suyunu çekene kadar kavurun, soğanı ekleyin.\n3. Salçayı ve rendelenmiş domatesleri ilave edip birkaç dakika pişirin.\n4. Nohutu ekleyip üzerini geçecek kadar su koyun, kısık ateşte 45 dakika pişirin.\n5. Tuzunu ayarlayıp servis edin.",
    },
    {
        "name": "Barbunya Pilaki",
        "desc": "Havuçlu, patatesli zeytinyağlı barbunya; soğuk da sıcak da yenir.",
        "region": "ege", "categories": ["baklagil"],
        "prep": 20, "cook": 45, "servings": 4, "cost": 140,
        "nutrition": (260, 12, 34, 9, 11),
        "ingredients": [("Barbunya", 300), ("Soğan", 1), ("Havuç", 1), ("Patates", 1), ("Domates", 2), ("Sarımsak", 3), ("Zeytinyağı", 4), ("Şeker", 5), ("Maydanoz", 0.5), ("Tuz", 1)],
        "recipe": "1. Barbunyayı ıslatıp haşlayın.\n2. Zeytinyağında soğanı ve sarımsağı kavurun, küp doğranmış havuç ve patatesi ekleyin.\n3. Rendelenmiş domatesi, barbunyayı, şekeri ve tuzu ilave edin.\n4. Üzerini geçecek kadar su ekleyip sebzeler yumuşayana kadar 30 dakika pişirin.\n5. Ilıyınca ince kıyılmış maydanozla servis edin.",
    },
    {
        "name": "Yeşil Mercimek Yemeği",
        "desc": "Soğanlı, sarımsaklı, yanına pilav yakışan mercimek yemeği.",
        "region": "turkiye", "categories": ["baklagil"],
        "prep": 10, "cook": 40, "servings": 4, "cost": 100,
        "nutrition": (280, 16, 42, 6, 14),
        "ingredients": [("Yeşil mercimek", 250), ("Soğan", 2), ("Sarımsak", 2), ("Salça", 1), ("Zeytinyağı", 3), ("Tuz", 1), ("Kimyon", 0.5)],
        "recipe": "1. Mercimeği yıkayıp 15 dakika haşlayın.\n2. Zeytinyağında soğanı ve sarımsağı kavurun, salçayı ekleyin.\n3. Mercimeği suyuyla birlikte ilave edin.\n4. Yaklaşık 20 dakika daha pişirip tuz ve kimyonla tatlandırın.\n5. Pilav ve cacıkla servis edin.",
    },
    {
        "name": "Mercimek Köftesi",
        "desc": "Kırmızı mercimek ve ince bulgurla yapılan, marulla sarılan köfte.",
        "region": "guneydogu", "categories": ["baklagil"],
        "prep": 30, "cook": 25, "servings": 4, "cost": 110,
        "nutrition": (290, 11, 47, 7, 9),
        "ingredients": [("Kırmızı mercimek", 200), ("İnce bulgur", 150), ("Soğan", 1), ("Taze soğan", 1), ("Salça", 1), ("Biber salçası", 1), ("Zeytinyağı", 3), ("Maydanoz", 0.5), ("Limon", 1), ("Marul", 1), ("Kimyon", 1), ("Pul biber", 1), ("Tuz", 1)],
        "recipe": "1. Mercimeği 3 su bardağı suda çok yumuşayana kadar pişirin, ocaktan alıp ince bulguru ekleyin ve kapağını kapatıp 15 dakika demlendirin.\n2. Zeytinyağında soğanı ve salçaları kavurup mercimeğe ekleyin.\n3. Baharatları, ince kıyılmış taze soğan ve maydanozu katıp yoğurun.\n4. Elinizle köfte şekli verin.\n5. Marul yapraklarında limonla servis edin.",
    },
    {
        "name": "Ispanaklı Nohut",
        "desc": "Ege usulü, limonlu ıspanaklı nohut yemeği.",
        "region": "ege", "categories": ["baklagil", "sebze"],
        "prep": 20, "cook": 55, "servings": 4, "cost": 150,
        "nutrition": (280, 15, 36, 9, 11),
        "ingredients": [("Nohut", 250), ("Ispanak", 500), ("Soğan", 2), ("Salça", 1), ("Zeytinyağı", 3), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Nohutu ıslatıp yumuşayana kadar haşlayın.\n2. Zeytinyağında soğanı kavurun, salçayı ekleyin.\n3. Yıkayıp doğradığınız ıspanağı ekleyip suyunu salıp çekene kadar pişirin.\n4. Nohutu ve biraz haşlama suyunu ilave edip 15 dakika pişirin.\n5. Tuz ve limonla servis edin.",
    },
    {
        "name": "Kuru Börülce Yemeği",
        "desc": "Havuçlu, dereotlu zeytinyağlı kuru börülce.",
        "region": "ege", "categories": ["baklagil"],
        "prep": 15, "cook": 50, "servings": 4, "cost": 140,
        "nutrition": (270, 14, 38, 8, 10),
        "ingredients": [("Kuru börülce", 300), ("Soğan", 2), ("Havuç", 1), ("Domates", 1), ("Sarımsak", 2), ("Zeytinyağı", 3), ("Dereotu", 0.5), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Börülceyi bir gece ıslatıp haşlayın.\n2. Zeytinyağında soğanı, sarımsağı ve havucu kavurun.\n3. Domatesi ve börülceyi ekleyip biraz su ilave edin, 25 dakika pişirin.\n4. Tuzu ve dereotunu ekleyin.\n5. Limon sıkarak servis edin.",
    },
    {
        "name": "Mercimekli Bulgur Pilavı",
        "desc": "Yeşil mercimekle zenginleşen tam öğün bulgur pilavı.",
        "region": "turkiye", "categories": ["baklagil", "pilav-makarna"],
        "prep": 10, "cook": 35, "servings": 4, "cost": 90,
        "nutrition": (330, 13, 58, 6, 10),
        "ingredients": [("Yeşil mercimek", 100), ("Bulgur", 250), ("Soğan", 1), ("Salça", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Mercimeği 15 dakika haşlayıp süzün, haşlama suyunu saklayın.\n2. Tereyağında soğanı kavurun, salçayı ekleyin.\n3. Bulguru ve mercimeği ilave edip 2 dakika çevirin.\n4. Mercimeğin haşlama suyunu ve sıcak suyu toplam 4 su bardağı olacak şekilde ekleyin, tuzlayın.\n5. Kısık ateşte suyunu çekene kadar pişirip 10 dakika demlendirin.",
    },
]
