MEALS = [
    {
        "name": "Mercimek Çorbası",
        "desc": "Türk sofrasının vazgeçilmezi, süzülmüş kırmızı mercimek çorbası.",
        "region": "turkiye", "categories": ["corba", "baklagil"],
        "prep": 10, "cook": 25, "servings": 4, "cost": 90,
        "nutrition": (200, 11, 30, 4, 7),
        "ingredients": [("Kırmızı mercimek", 200), ("Soğan", 1), ("Havuç", 1), ("Patates", 1), ("Tereyağı", 1), ("Salça", 1), ("Tuz", 1), ("Limon", 1)],
        "recipe": "1. Soğanı, havucu ve patatesi küçük küçük doğrayın.\n2. Tereyağında soğanı kavurun, salçayı ekleyip kokusu çıkana kadar pişirin.\n3. Yıkadığınız mercimeği ve sebzeleri ekleyin, 6 su bardağı sıcak su koyup sebzeler yumuşayana kadar yaklaşık 25 dakika pişirin.\n4. Blenderdan geçirip tuzunu ayarlayın.\n5. Limon sıkarak servis edin.",
    },
    {
        "name": "Ezogelin Çorbası",
        "desc": "Mercimek, bulgur ve pirinçle yapılan, naneli baharatlı çorba.",
        "region": "guneydogu", "categories": ["corba", "baklagil"],
        "prep": 10, "cook": 30, "servings": 4, "cost": 85,
        "nutrition": (230, 10, 38, 4, 7),
        "ingredients": [("Kırmızı mercimek", 150), ("Bulgur", 40), ("Pirinç", 30), ("Soğan", 1), ("Salça", 1), ("Biber salçası", 1), ("Tereyağı", 1), ("Kuru nane", 1), ("Pul biber", 1), ("Tuz", 1)],
        "recipe": "1. Mercimeği, bulguru ve pirinci yıkayın.\n2. Yağda ince doğranmış soğanı kavurun, salçaları ekleyip biraz daha pişirin.\n3. Yıkanmış malzemeleri ve 7 su bardağı sıcak suyu ilave edip kısık ateşte yaklaşık 30 dakika pişirin.\n4. Tuzunu ekleyin.\n5. Ayrı bir tavada tereyağında nane ve pul biberi yakıp çorbanın üzerine gezdirin.",
    },
    {
        "name": "Domates Çorbası",
        "desc": "Taze domatesli, kaşar peynirli kremamsı çorba.",
        "region": "turkiye", "categories": ["corba"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 80,
        "nutrition": (150, 6, 18, 7, 2),
        "ingredients": [("Domates", 5), ("Un", 25), ("Tereyağı", 1), ("Süt", 250), ("Kaşar peyniri", 40), ("Tuz", 1)],
        "recipe": "1. Domatesleri rendeleyin veya haşlayıp kabuklarını soyun.\n2. Tereyağında unu hafifçe kavurun, domatesleri ekleyin.\n3. 3 su bardağı su ekleyip 15 dakika kaynatın.\n4. Sütü ekleyip birkaç dakika daha pişirin, tuzunu ayarlayın.\n5. Üzerine rendelenmiş kaşar serperek servis edin.",
    },
    {
        "name": "Tarhana Çorbası",
        "desc": "Ekşimsi tadıyla kış sofralarının klasiği, geleneksel tarhana çorbası.",
        "region": "ic-anadolu", "categories": ["corba"],
        "prep": 5, "cook": 15, "servings": 4, "cost": 70,
        "nutrition": (170, 6, 26, 5, 2),
        "ingredients": [("Tarhana", 100), ("Tereyağı", 1), ("Salça", 1), ("Kuru nane", 1), ("Tuz", 1)],
        "recipe": "1. Tarhanayı 2 su bardağı soğuk suda çözün.\n2. Tereyağında salçayı kavurun, tarhanalı karışımı ve 4 su bardağı sıcak suyu ekleyin.\n3. Sürekli karıştırarak kaynamaya bırakın, 10-15 dakika pişirin.\n4. Tuzunu ayarlayıp naneyle servis edin.",
    },
    {
        "name": "Yayla Çorbası",
        "desc": "Yoğurtlu, pirinçli, naneli hafif bir çorba.",
        "region": "ic-anadolu", "categories": ["corba"],
        "prep": 10, "cook": 25, "servings": 4, "cost": 85,
        "nutrition": (210, 8, 26, 8, 1),
        "ingredients": [("Pirinç", 60), ("Yoğurt", 300), ("Yumurta", 1), ("Un", 15), ("Tereyağı", 1), ("Kuru nane", 1), ("Tuz", 1)],
        "recipe": "1. Pirinci 5 su bardağı suda yumuşayana kadar haşlayın.\n2. Yoğurt, yumurta ve unu çırpın; üzerine bir kepçe sıcak çorba ekleyip karıştırın (ısıya alıştırın).\n3. Karışımı yavaşça tencereye ekleyip kesilmemesi için sürekli karıştırarak 5 dakika pişirin.\n4. Tuzunu ayarlayın.\n5. Tereyağında naneyi kızdırıp üzerine gezdirin.",
    },
    {
        "name": "Düğün Çorbası",
        "desc": "Etli, yumurta sarılı ve limonlu, adını şenlik sofralarından alan çorba.",
        "region": "ic-anadolu", "categories": ["corba"],
        "prep": 15, "cook": 60, "servings": 4, "cost": 190,
        "nutrition": (260, 15, 18, 14, 1),
        "ingredients": [("Kuşbaşı et", 200), ("Un", 40), ("Yumurta sarısı", 2), ("Limon", 1), ("Tereyağı", 2), ("Toz kırmızı biber", 1), ("Tuz", 1)],
        "recipe": "1. Eti bol suda yumuşayana kadar (yaklaşık 45 dakika) haşlayın, suyunu süzüp eti didikleyin.\n2. Tereyağında unu kokusu çıkana kadar kavurun, et suyunu azar azar ekleyerek karıştırın.\n3. Didiklenmiş eti ekleyip 10 dakika kaynatın.\n4. Yumurta sarılarını limon suyuyla çırpın, bir kepçe sıcak çorbayla ısıtıp çorbaya ekleyin.\n5. Tereyağında kırmızı biberi yakıp üzerine gezdirin.",
    },
    {
        "name": "Şehriye Çorbası",
        "desc": "Domatesli, tereyağlı hafif şehriye çorbası.",
        "region": "turkiye", "categories": ["corba"],
        "prep": 5, "cook": 15, "servings": 4, "cost": 60,
        "nutrition": (150, 4, 26, 3, 2),
        "ingredients": [("Şehriye", 80), ("Domates", 2), ("Salça", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Tereyağında şehriyeyi kızarana kadar kavurun.\n2. Salçayı ve rendelenmiş domatesleri ekleyip 2 dakika pişirin.\n3. 5 su bardağı sıcak su ekleyip şehriyeler yumuşayana kadar 10 dakika kaynatın.\n4. Tuzunu ayarlayıp sıcak servis edin.",
    },
    {
        "name": "Sebze Çorbası",
        "desc": "Mevsim sebzeleriyle hafif ve doyurucu çorba.",
        "region": "turkiye", "categories": ["corba", "sebze"],
        "prep": 15, "cook": 25, "servings": 4, "cost": 90,
        "nutrition": (120, 4, 18, 4, 4),
        "ingredients": [("Havuç", 1), ("Patates", 1), ("Kabak", 1), ("Soğan", 1), ("Bezelye", 100), ("Domates", 1), ("Zeytinyağı", 2), ("Maydanoz", 0.5), ("Tuz", 1)],
        "recipe": "1. Tüm sebzeleri küçük küp doğrayın.\n2. Zeytinyağında soğanı kavurun, diğer sebzeleri ekleyip 3-4 dakika çevirin.\n3. 6 su bardağı sıcak su ekleyip sebzeler yumuşayana kadar 20 dakika pişirin.\n4. Tuzunu ayarlayın, ince kıyılmış maydanozla servis edin.",
    },
    {
        "name": "Kremalı Mantar Çorbası",
        "desc": "Kremamsı dokusuyla mantar çorbası.",
        "region": "turkiye", "categories": ["corba"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 100,
        "nutrition": (140, 5, 14, 7, 2),
        "ingredients": [("Mantar", 300), ("Soğan", 1), ("Un", 30), ("Tereyağı", 1), ("Süt", 500), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Mantarları ve soğanı ince doğrayın.\n2. Tereyağında soğanı, ardından mantarları suyunu çekene kadar kavurun.\n3. Unu ekleyip 1 dakika çevirin, sütü ve 2 su bardağı suyu ekleyerek kaynatın.\n4. 15 dakika pişirip blenderdan geçirin.\n5. Tuz ve karabiberle servis edin.",
    },
    {
        "name": "Brokoli Çorbası",
        "desc": "Patatesle kıvam alan, besleyici brokoli çorbası.",
        "region": "turkiye", "categories": ["corba", "sebze"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 90,
        "nutrition": (130, 5, 14, 6, 4),
        "ingredients": [("Brokoli", 400), ("Patates", 1), ("Soğan", 1), ("Zeytinyağı", 2), ("Süt", 200), ("Tuz", 1)],
        "recipe": "1. Brokoliyi çiçeklerine ayırın, patatesi ve soğanı doğrayın.\n2. Zeytinyağında soğanı kavurun, patates ve brokoliyi ekleyin.\n3. Sebzelerin üzerini geçecek kadar su ekleyip 15 dakika pişirin.\n4. Blenderdan geçirin, sütü ekleyip ısıtın, tuzunu ayarlayın.",
    },
    {
        "name": "Kara Lahana Çorbası",
        "desc": "Karadeniz'in mısır unlu, kuru fasulyeli kış çorbası.",
        "region": "karadeniz", "categories": ["corba", "sebze", "baklagil"],
        "prep": 20, "cook": 60, "servings": 4, "cost": 110,
        "nutrition": (220, 9, 32, 6, 9),
        "ingredients": [("Kara lahana", 400), ("Kuru fasulye", 100), ("Mısır unu", 40), ("Soğan", 1), ("Tereyağı", 1), ("Salça", 1), ("Pul biber", 1), ("Tuz", 1)],
        "recipe": "1. Kuru fasulyeyi bir gece önceden ıslatıp yarı yumuşayana kadar haşlayın.\n2. Kara lahanayı yıkayıp ince doğrayın.\n3. Tereyağında soğanı ve salçayı kavurun, lahanayı ve fasulyeyi haşlama suyuyla birlikte ekleyin.\n4. Mısır ununu az suda açıp çorbaya ekleyin, karıştırarak 30 dakika pişirin.\n5. Tuzunu ayarlayıp pul biberle servis edin.",
    },
    {
        "name": "Tel Şehriyeli Tavuk Çorbası",
        "desc": "Limonlu, yumurta sarılı şifalı tavuk çorbası.",
        "region": "turkiye", "categories": ["corba"],
        "prep": 10, "cook": 30, "servings": 4, "cost": 130,
        "nutrition": (170, 16, 14, 5, 1),
        "ingredients": [("Tavuk göğsü", 200), ("Şehriye", 60), ("Havuç", 1), ("Yumurta sarısı", 1), ("Limon", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Tavuğu ve havucu 6 su bardağı suda haşlayın, tavuğu didikleyin.\n2. Tereyağında şehriyeyi kavurup tavuk suyuna ekleyin ve 10 dakika pişirin.\n3. Didiklenmiş tavuğu ekleyin.\n4. Yumurta sarısını limon suyuyla çırpıp bir kepçe çorbayla ısıtarak çorbaya ilave edin.\n5. Tuzunu ayarlayın.",
    },
]
