MEALS = [
    {
        "name": "İzmir Köfte",
        "desc": "Patatesli, domates soslu fırın köfte.",
        "region": "ege", "categories": ["et"],
        "prep": 30, "cook": 40, "servings": 4, "cost": 300,
        "nutrition": (400, 25, 25, 22, 3),
        "ingredients": [("Kıyma", 400), ("Ekmek", 2), ("Soğan", 1), ("Sarımsak", 2), ("Maydanoz", 0.5), ("Kimyon", 1), ("Karabiber", 0.5), ("Tuz", 1), ("Patates", 3), ("Domates", 3), ("Yeşil biber", 3), ("Salça", 1), ("Sıvı yağ", 4)],
        "recipe": "1. Kıymayı ıslatıp sıkılmış ekmek içi, rendelenmiş soğan, sarımsak, maydanoz, kimyon, karabiber ve tuzla yoğurun.\n2. Uzunca köfteler yapın ve yağda hafifçe kızartın; patatesleri de dilimleyip kızartın.\n3. Tepsiye köfte, patates ve biberleri dizin.\n4. Salçayı ve rendelenmiş domatesi 1 su bardağı suyla karıştırıp üzerine dökün.\n5. 190 derece fırında 35-40 dakika pişirin.",
    },
    {
        "name": "Izgara Köfte",
        "desc": "Soğanlı, maydanozlu klasik ızgara köfte.",
        "region": "turkiye", "categories": ["et"],
        "prep": 20, "cook": 15, "servings": 4, "cost": 260,
        "nutrition": (330, 25, 10, 21, 1),
        "ingredients": [("Kıyma", 400), ("Soğan", 1), ("Ekmek", 2), ("Maydanoz", 0.5), ("Kimyon", 1), ("Karabiber", 0.5), ("Tuz", 1), ("Domates", 2), ("Yeşil biber", 3)],
        "recipe": "1. Kıymayı rendelenmiş soğan, ıslatılıp sıkılmış ekmek içi, kıyılmış maydanoz ve baharatlarla yoğurun.\n2. Yarım saat buzdolabında dinlendirin.\n3. Ceviz büyüklüğünde parçalar alıp köfte şekli verin.\n4. Izgarada veya tavada iki yüzünü de pişirin.\n5. Közlenmiş domates ve biberle servis edin.",
    },
    {
        "name": "Akçaabat Köfte",
        "desc": "Karadeniz'in ekmekli, baharatlı ızgara köftesi.",
        "region": "karadeniz", "categories": ["et"],
        "prep": 20, "cook": 20, "servings": 4, "cost": 270,
        "nutrition": (340, 26, 10, 22, 1),
        "ingredients": [("Kıyma", 400), ("Ekmek", 2), ("Soğan", 1), ("Karabiber", 1), ("Kimyon", 1), ("Tuz", 1), ("Yeşil biber", 3), ("Domates", 2)],
        "recipe": "1. Kıymayı ıslatılmış ekmek içi, rendelenmiş soğan ve baharatlarla uzun uzun yoğurun.\n2. Dolaba kaldırıp 1 saat dinlendirin.\n3. Yassı köfteler yapıp ızgarada iki yüzünü de pişirin.\n4. Közlenmiş biber ve domatesle sıcak servis edin.",
    },
    {
        "name": "Sulu Köfte",
        "desc": "Patatesli, havuçlu, salçalı sulu köfte.",
        "region": "ic-anadolu", "categories": ["et"],
        "prep": 25, "cook": 40, "servings": 4, "cost": 260,
        "nutrition": (330, 18, 26, 17, 3),
        "ingredients": [("Kıyma", 300), ("Pirinç", 40), ("Soğan", 1), ("Patates", 2), ("Havuç", 1), ("Un", 20), ("Salça", 1), ("Tereyağı", 1), ("Kuru nane", 1), ("Tuz", 1)],
        "recipe": "1. Kıymayı yıkanmış pirinç, rendelenmiş soğan ve tuzla yoğurup ceviz büyüklüğünde köfteler yapın, una bulayın.\n2. Tereyağında salçayı kavurun, 5 su bardağı sıcak su ekleyip kaynatın.\n3. Küp doğranmış patates ve havucu ekleyin.\n4. Köfteleri yavaşça bırakıp kısık ateşte 30 dakika pişirin.\n5. Naneyle servis edin.",
    },
    {
        "name": "Kadınbudu Köfte",
        "desc": "Pirinçli, yumurtalı kızarmış Bursa usulü köfte.",
        "region": "marmara", "categories": ["et"],
        "prep": 30, "cook": 20, "servings": 4, "cost": 280,
        "nutrition": (380, 20, 24, 22, 1),
        "ingredients": [("Kıyma", 300), ("Pirinç", 60), ("Yumurta", 2), ("Soğan", 1), ("Un", 40), ("Maydanoz", 0.5), ("Sıvı yağ", 4), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Pirinci yumuşayana kadar haşlayıp süzün.\n2. Kıyma, pirinç, rendelenmiş soğan, 1 yumurta, maydanoz ve baharatları yoğurun.\n3. Oval köfteler yapıp una, ardından çırpılmış yumurtaya bulayın.\n4. Kızgın yağda iki yüzünü de kızartın.",
    },
    {
        "name": "İçli Köfte",
        "desc": "İnce bulgur hamuru ve cevizli kıymalı iç harçla yapılan Güneydoğu klasiği.",
        "region": "guneydogu", "categories": ["et"],
        "prep": 60, "cook": 20, "servings": 4, "cost": 300,
        "nutrition": (450, 22, 42, 22, 5),
        "ingredients": [("İnce bulgur", 250), ("Kıyma", 250), ("Soğan", 2), ("Un", 30), ("Toz kırmızı biber", 1), ("Sıvı yağ", 6), ("Ceviz", 30), ("Maydanoz", 0.5), ("Tuz", 1), ("Karabiber", 1)],
        "recipe": "1. İç harç için soğanı ve kıymayı yağda kavurun, baharat, ceviz ve maydanozu ekleyip soğutun.\n2. İnce bulguru ılık suyla, una ve tuzla yoğurup hamur yapın.\n3. Hamurdan bezelerle çukur açıp içine harç koyun, kapatıp oval şekil verin.\n4. Kaynar tuzlu suda 15 dakika haşlayın veya kızgın yağda kızartın.",
    },
    {
        "name": "Orman Kebabı",
        "desc": "Sebzeli, etli Bursa usulü tencere yemeği.",
        "region": "marmara", "categories": ["et", "sebze"],
        "prep": 25, "cook": 60, "servings": 4, "cost": 440,
        "nutrition": (380, 29, 26, 17, 5),
        "ingredients": [("Kuşbaşı et", 400), ("Patates", 3), ("Havuç", 2), ("Bezelye", 100), ("Soğan", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Eti yağda suyunu çekene kadar kavurun, soğanı ve salçayı ekleyin.\n2. 2 su bardağı sıcak su ekleyip eti 30 dakika pişirin.\n3. Küp doğranmış patates ve havuçları, bezelyeyi ekleyin, tuzlayın.\n4. Sebzeler yumuşayana kadar 25 dakika daha pişirin.",
    },
    {
        "name": "Tas Kebabı",
        "desc": "Domatesli, biberli, yumuşak kuşbaşı et yemeği.",
        "region": "ic-anadolu", "categories": ["et"],
        "prep": 15, "cook": 75, "servings": 4, "cost": 470,
        "nutrition": (350, 32, 8, 21, 2),
        "ingredients": [("Kuşbaşı et", 450), ("Soğan", 2), ("Domates", 2), ("Yeşil biber", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Eti yağda ve tereyağında suyunu çekene kadar kavurun.\n2. Yarım ay doğranmış soğanı ve salçayı ekleyin.\n3. Rendelenmiş domates ve biberleri ilave edip 2 su bardağı sıcak su koyun.\n4. Kısık ateşte 60 dakika, et yumuşayana kadar pişirin.\n5. Pilavla servis edin.",
    },
    {
        "name": "Hünkar Beğendi",
        "desc": "Közlenmiş patlıcan püresi yatağında et yahnisi.",
        "region": "marmara", "categories": ["et", "sebze"],
        "prep": 30, "cook": 60, "servings": 4, "cost": 520,
        "nutrition": (470, 30, 20, 30, 5),
        "ingredients": [("Kuşbaşı et", 400), ("Patlıcan", 4), ("Süt", 200), ("Un", 25), ("Tereyağı", 2), ("Kaşar peyniri", 60), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Eti yağda kavurun, soğanı, salçayı ve domatesi ekleyin; 2 su bardağı su koyup yumuşayana kadar 50 dakika pişirin.\n2. Patlıcanları közleyip kabuğunu soyun, ezin.\n3. Tereyağında unu kavurun, sütü azar azar ekleyip sos yapın; patlıcanı ve rendelenmiş kaşarı katıp karıştırın.\n4. Püreyi tabağa yayın, üzerine eti yerleştirin.",
    },
    {
        "name": "Kuzu Tandır",
        "desc": "Fırında saatlerce pişen, çatalla ayrılan kuzu.",
        "region": "ic-anadolu", "categories": ["et"],
        "prep": 20, "cook": 180, "servings": 4, "cost": 1100,
        "nutrition": (560, 45, 4, 40, 1),
        "ingredients": [("Kuzu eti", 1000), ("Soğan", 2), ("Sarımsak", 4), ("Tereyağı", 2), ("Tuz", 1), ("Karabiber", 1), ("Kekik", 1)],
        "recipe": "1. Eti tuz, karabiber, kekik ve ezilmiş sarımsakla ovup tereyağıyla harmanlayın.\n2. Soğan halkalarının üzerine yerleştirip 1 su bardağı su ekleyin.\n3. Folyoyla sıkıca kapatıp 160 derecede 2,5-3 saat pişirin.\n4. Folyoyu açıp son 15 dakikada üzerini kızartın.",
    },
    {
        "name": "Etli Güveç",
        "desc": "Sebzeli, fırında pişen kuşbaşı etli güveç.",
        "region": "turkiye", "categories": ["et", "sebze"],
        "prep": 25, "cook": 90, "servings": 4, "cost": 470,
        "nutrition": (390, 28, 24, 20, 4),
        "ingredients": [("Kuşbaşı et", 400), ("Patates", 2), ("Havuç", 1), ("Domates", 2), ("Soğan", 2), ("Yeşil biber", 2), ("Sarımsak", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Eti yağda suyunu çekene kadar kavurun, salçayı ekleyin.\n2. Doğranmış sebzeleri ve sarımsağı güveç kabına koyun, eti ekleyip tuzlayın.\n3. 1 su bardağı sıcak su ilave edin.\n4. Kapağı kapalı 180 derece fırında 80-90 dakika pişirin.",
    },
    {
        "name": "Et Sote",
        "desc": "Biberli, domatesli, hızlı pişen kuşbaşı sote.",
        "region": "turkiye", "categories": ["et"],
        "prep": 15, "cook": 45, "servings": 4, "cost": 560,
        "nutrition": (330, 32, 7, 19, 2),
        "ingredients": [("Kuşbaşı et", 500), ("Soğan", 2), ("Yeşil biber", 3), ("Domates", 2), ("Sarımsak", 2), ("Tereyağı", 1), ("Sıvı yağ", 1), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Eti yüksek ateşte tereyağı ve yağla suyunu çekip kızarana kadar kavurun, gerekirse biraz su ekleyip yumuşatın.\n2. Soğanı ve sarımsağı ekleyin.\n3. Biberleri ve doğranmış domatesi ilave edin.\n4. Tuz ve karabiberle tatlandırıp 10 dakika daha pişirin.",
    },
    {
        "name": "Kağıt Kebabı",
        "desc": "Pişirme kâğıdında sebzelerle pişen et.",
        "region": "akdeniz", "categories": ["et"],
        "prep": 25, "cook": 60, "servings": 4, "cost": 480,
        "nutrition": (370, 29, 20, 19, 3),
        "ingredients": [("Kuşbaşı et", 400), ("Patates", 2), ("Domates", 2), ("Yeşil biber", 2), ("Soğan", 1), ("Sarımsak", 2), ("Tereyağı", 1), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Eti tereyağında hafifçe kavurun.\n2. Küp doğranmış patates, biber, soğan, domates ve sarımsakla karıştırıp tuzlayın.\n3. Yağlı kâğıdı ıslatıp harcı içine koyun ve ağzını sıkıca bağlayın.\n4. Tepsiye alıp 180 derece fırında 55-60 dakika pişirin.",
    },
    {
        "name": "Adana Kebap",
        "desc": "Acılı, elde şişe geçirilmiş Adana kebabı.",
        "region": "akdeniz", "categories": ["et"],
        "prep": 25, "cook": 15, "servings": 4, "cost": 500,
        "nutrition": (450, 30, 22, 26, 2),
        "ingredients": [("Kıyma", 500), ("Pul biber", 2), ("Toz kırmızı biber", 2), ("Tuz", 1), ("Biber salçası", 1), ("Domates", 2), ("Yeşil biber", 3), ("Soğan", 1), ("Sumak", 1), ("Lavaş", 4)],
        "recipe": "1. Kıymayı biberler, salça ve tuzla uzun süre yoğurun.\n2. Şişlere uzun uzun sarıp ızgarada kızartın.\n3. Domates ve biberleri de ızgarada közleyin.\n4. Soğanı sumakla harmanlayın.\n5. Lavaş, közlenmiş sebze ve soğanla servis edin.",
    },
    {
        "name": "Urfa Kebap",
        "desc": "Acısız, sade baharatlı Urfa kebabı.",
        "region": "guneydogu", "categories": ["et"],
        "prep": 25, "cook": 15, "servings": 4, "cost": 500,
        "nutrition": (440, 30, 20, 25, 2),
        "ingredients": [("Kıyma", 500), ("Soğan", 1), ("Tuz", 1), ("Karabiber", 1), ("Lavaş", 4), ("Domates", 2), ("Yeşil biber", 3), ("Sumak", 1)],
        "recipe": "1. Kıymayı rendelenmiş soğan, tuz ve karabiberle uzun süre yoğurun.\n2. Şişlere geçirip ızgarada pişirin.\n3. Domates ve biberi közleyin.\n4. Lavaşla, sumaklı soğanla servis edin.",
    },
    {
        "name": "Ali Nazik",
        "desc": "Sarımsaklı yoğurtlu közlenmiş patlıcan üzerinde kıymalı sote.",
        "region": "guneydogu", "categories": ["et", "sebze"],
        "prep": 25, "cook": 30, "servings": 4, "cost": 340,
        "nutrition": (400, 24, 14, 28, 5),
        "ingredients": [("Kıyma", 300), ("Patlıcan", 4), ("Yoğurt", 300), ("Sarımsak", 3), ("Tereyağı", 2), ("Domates", 1), ("Sıvı yağ", 1), ("Tuz", 1)],
        "recipe": "1. Patlıcanları közleyip kabuğunu soyun, ince kıyıp ezin.\n2. Yoğurdu ezilmiş sarımsak ve tuzla karıştırıp patlıcanla harmanlayın.\n3. Yağda kıymayı ve rendelenmiş domatesi pişirin.\n4. Tabağa patlıcanlı yoğurdu yayıp üzerine sıcak kıymayı koyun, eritilmiş tereyağı gezdirin.",
    },
    {
        "name": "Beyti Sarma",
        "desc": "Lavaşa sarılan baharatlı köfte, yoğurt ve domates soslu.",
        "region": "marmara", "categories": ["et"],
        "prep": 30, "cook": 30, "servings": 4, "cost": 380,
        "nutrition": (520, 26, 32, 30, 2),
        "ingredients": [("Kıyma", 400), ("Lavaş", 4), ("Sarımsak", 2), ("Maydanoz", 0.5), ("Toz kırmızı biber", 1), ("Tereyağı", 2), ("Domates", 2), ("Yoğurt", 200), ("Tuz", 1)],
        "recipe": "1. Kıymayı sarımsak, maydanoz, biber ve tuzla yoğurup şişe uzun uzun sarın; ızgarada veya tavada pişirin.\n2. Pişen kebabı lavaşa sarıp 3-4 cm'lik parçalara kesin.\n3. Tereyağında rendelenmiş domates sosu hazırlayın.\n4. Tabağa dizip domates sosu ve yoğurtla servis edin.",
    },
    {
        "name": "İskender Kebap",
        "desc": "Pide üzerinde dilimli et, domates sosu ve tereyağı.",
        "region": "marmara", "categories": ["et"],
        "prep": 25, "cook": 25, "servings": 4, "cost": 650,
        "nutrition": (600, 38, 26, 36, 2),
        "ingredients": [("Dana bonfile", 400), ("Ekmek", 4), ("Tereyağı", 3), ("Salça", 1), ("Domates", 2), ("Yoğurt", 300), ("Yeşil biber", 2), ("Tuz", 1)],
        "recipe": "1. Bonfileyi ince dilimleyip tuzla tavada kavurun.\n2. Ekmek dilimlerini tabağa dizin.\n3. Salça ve rendelenmiş domatesle sos hazırlayıp ekmeklerin üzerine dökün.\n4. Üzerine etleri yerleştirin, yanına yoğurt ve közlenmiş biber koyun.\n5. Kızdırılmış tereyağını gezdirip hemen servis edin.",
    },
    {
        "name": "Çökertme Kebabı",
        "desc": "Çıtır patates yatağında dana eti ve yoğurt.",
        "region": "ege", "categories": ["et"],
        "prep": 25, "cook": 30, "servings": 4, "cost": 650,
        "nutrition": (610, 35, 30, 38, 3),
        "ingredients": [("Dana bonfile", 400), ("Patates", 3), ("Yoğurt", 250), ("Sarımsak", 2), ("Sıvı yağ", 4), ("Domates", 2), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Patatesleri kibrit gibi doğrayıp kızgın yağda çıtır çıtır kızartın.\n2. Bonfileyi ince şeritler halinde tereyağında kavurun.\n3. Yoğurdu ezilmiş sarımsak ve tuzla karıştırın.\n4. Tabağa patatesleri koyup üzerine et, yanına yoğurt ve közlenmiş domates ekleyin.",
    },
    {
        "name": "Tantuni",
        "desc": "Mersin usulü baharatlı dana eti dürüm.",
        "region": "akdeniz", "categories": ["et"],
        "prep": 20, "cook": 15, "servings": 4, "cost": 480,
        "nutrition": (430, 28, 32, 22, 3),
        "ingredients": [("Dana bonfile", 300), ("Lavaş", 4), ("Domates", 2), ("Yeşil biber", 2), ("Soğan", 1), ("Maydanoz", 0.5), ("Sumak", 1), ("Pul biber", 1), ("Sıvı yağ", 3), ("Tuz", 1)],
        "recipe": "1. Bonfileyi çok ince doğrayıp yağda yüksek ateşte pul biber ve tuzla kavurun.\n2. Domates, biber, soğan ve maydanozu doğrayıp sumakla karıştırın.\n3. Lavaşı ısıtıp içine et ve sebze karışımını koyun.\n4. Dürüm yapıp servis edin.",
    },
    {
        "name": "Etli Ekmek",
        "desc": "Konya usulü ince açılmış hamur üzerinde kıymalı harç.",
        "region": "ic-anadolu", "categories": ["et", "hamur-isi"],
        "prep": 40, "cook": 15, "servings": 4, "cost": 300,
        "nutrition": (480, 22, 50, 20, 3),
        "ingredients": [("Pide hamuru", 4), ("Kıyma", 300), ("Soğan", 2), ("Domates", 2), ("Yeşil biber", 2), ("Maydanoz", 1), ("Biber salçası", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Kıymayı ince doğranmış soğan, domates, biber, maydanoz, salça ve tuzla yoğurun.\n2. Hamur toplarını uzun ve ince açın.\n3. Harcı hamurun üzerine ince bir tabaka halinde yayın.\n4. 250 derece fırında 12-15 dakika pişirin.\n5. Üzerine eritilmiş tereyağı sürüp servis edin.",
    },
    {
        "name": "Kayseri Mantısı",
        "desc": "Minik mantılar, sarımsaklı yoğurt ve tereyağlı salça sosuyla.",
        "region": "ic-anadolu", "categories": ["et", "pilav-makarna", "hamur-isi"],
        "prep": 60, "cook": 20, "servings": 4, "cost": 240,
        "nutrition": (490, 24, 60, 16, 3),
        "ingredients": [("Un", 300), ("Yumurta", 1), ("Kıyma", 200), ("Soğan", 1), ("Yoğurt", 300), ("Sarımsak", 2), ("Tereyağı", 2), ("Salça", 1), ("Pul biber", 1), ("Kuru nane", 1), ("Tuz", 1)],
        "recipe": "1. Un, yumurta, tuz ve suyla sert bir hamur yoğurup dinlendirin.\n2. Kıymayı rendelenmiş soğan ve tuzla harmanlayın.\n3. Hamuru ince açıp küçük kareler kesin, içine harç koyup kapatın.\n4. Mantıları fırında kızartıp kaynar tuzlu suda 10 dakika haşlayın.\n5. Sarımsaklı yoğurtla servis edip tereyağında salça, pul biber ve nane sosu gezdirin.",
    },
    {
        "name": "Cağ Kebabı",
        "desc": "Erzurum usulü yatay şişte pişen kuzu eti.",
        "region": "dogu-anadolu", "categories": ["et"],
        "prep": 30, "cook": 30, "servings": 4, "cost": 800,
        "nutrition": (520, 40, 26, 28, 2),
        "ingredients": [("Kuzu eti", 600), ("Soğan", 2), ("Tuz", 1), ("Karabiber", 1), ("Lavaş", 4), ("Domates", 2), ("Yeşil biber", 2)],
        "recipe": "1. Kuzu etini rendelenmiş soğan, tuz ve karabiberle 3-4 saat marine edin.\n2. Şişlere dizin.\n3. Yüksek ateşte, sık çevirerek pişirin (ev tipi ızgara veya fırın).\n4. Lavaşa sarıp domates ve biberle servis edin.",
    },
    {
        "name": "Lahmacun",
        "desc": "İnce hamur üzerinde baharatlı kıymalı harç.",
        "region": "guneydogu", "categories": ["et", "hamur-isi"],
        "prep": 45, "cook": 15, "servings": 4, "cost": 220,
        "nutrition": (420, 22, 52, 14, 3),
        "ingredients": [("Un", 300), ("Kuru maya", 1), ("Kıyma", 250), ("Soğan", 2), ("Domates", 2), ("Yeşil biber", 2), ("Sarımsak", 2), ("Maydanoz", 1), ("Biber salçası", 1), ("Pul biber", 1), ("Tuz", 1), ("Limon", 1), ("Sıvı yağ", 2)],
        "recipe": "1. Un, maya, tuz ve ılık sudan hamur yoğurup 30 dakika mayalandırın.\n2. Kıyma, ince doğranmış soğan, domates, biber, sarımsak, maydanoz, salça, pul biber ve yağı karıştırın.\n3. Hamuru ince açın ve harcı yayın.\n4. 250 derece fırında 8-10 dakika pişirin.\n5. Maydanoz ve limonla sarıp yiyin.",
    },
    {
        "name": "Hatay Tepsi Kebabı",
        "desc": "Kıyma, domates ve biberle tepside pişen kebap.",
        "region": "akdeniz", "categories": ["et"],
        "prep": 25, "cook": 35, "servings": 4, "cost": 380,
        "nutrition": (350, 22, 12, 24, 3),
        "ingredients": [("Kıyma", 400), ("Soğan", 2), ("Domates", 3), ("Yeşil biber", 3), ("Maydanoz", 1), ("Biber salçası", 1), ("Kimyon", 1), ("Pul biber", 1), ("Tuz", 1), ("Sıvı yağ", 2)],
        "recipe": "1. Kıymayı ince doğranmış soğan, maydanoz, salça, kimyon, pul biber ve tuzla yoğurun.\n2. Tepsiye ince yayıp bıçakla dilimleyin.\n3. Aralarına domates ve biber dilimleri yerleştirin.\n4. Yağ gezdirip 200 derece fırında 30-35 dakika pişirin.",
    },
    {
        "name": "Tokat Kebabı",
        "desc": "Kuzu eti, patlıcan, patates ve domatesle tepside.",
        "region": "karadeniz", "categories": ["et", "sebze"],
        "prep": 30, "cook": 60, "servings": 4, "cost": 520,
        "nutrition": (480, 30, 30, 26, 5),
        "ingredients": [("Kuşbaşı et", 400), ("Patlıcan", 2), ("Patates", 3), ("Domates", 3), ("Sarımsak", 4), ("Sıvı yağ", 4), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Etleri tereyağında hafifçe kavurun.\n2. Patates ve patlıcanı yağda kızartın.\n3. Tepsiye etleri, patates ve patlıcanı, sarımsaklı domates dilimlerini dizin.\n4. Yarım su bardağı su gezdirip tuzlayın.\n5. 200 derece fırında 50 dakika pişirin.",
    },
    {
        "name": "Kavurma",
        "desc": "Kendi yağında pişen, soğuğa da dayanan et kavurması.",
        "region": "ic-anadolu", "categories": ["et"],
        "prep": 10, "cook": 70, "servings": 4, "cost": 550,
        "nutrition": (380, 34, 3, 26, 0),
        "ingredients": [("Kuşbaşı et", 500), ("Soğan", 1), ("Tereyağı", 2), ("Tuz", 1), ("Karabiber", 1), ("Kekik", 1)],
        "recipe": "1. Eti kalın tabanlı tencerede kendi suyunda kapağı kapalı yumuşayana kadar (yaklaşık 50 dakika) pişirin.\n2. Suyu çekince tereyağı ekleyip yüksek ateşte kavurun.\n3. Soğanı ve baharatları ekleyip kızarana kadar çevirin.\n4. Sıcak servis edin.",
    },
    {
        "name": "Ankara Tava",
        "desc": "Patlıcanlı, biberli, kuzu etli tepsi yemeği.",
        "region": "ic-anadolu", "categories": ["et", "sebze"],
        "prep": 25, "cook": 60, "servings": 4, "cost": 620,
        "nutrition": (420, 31, 18, 25, 5),
        "ingredients": [("Kuşbaşı et", 500), ("Patlıcan", 2), ("Domates", 2), ("Yeşil biber", 2), ("Soğan", 2), ("Sarımsak", 2), ("Sıvı yağ", 3), ("Tuz", 1)],
        "recipe": "1. Eti yağda suyunu çekene kadar kavurun, soğanı ekleyin.\n2. Küp doğranmış patlıcanı, biberi ve sarımsağı ekleyip birkaç dakika çevirin.\n3. Doğranmış domates ve tuzu ilave edin.\n4. Az su ekleyip kısık ateşte 50 dakika pişirin.",
    },
    {
        "name": "Kıymalı Pide",
        "desc": "Karadeniz usulü kayık şeklinde kıymalı pide.",
        "region": "karadeniz", "categories": ["et", "hamur-isi"],
        "prep": 45, "cook": 15, "servings": 4, "cost": 230,
        "nutrition": (480, 23, 54, 18, 3),
        "ingredients": [("Un", 350), ("Kuru maya", 1), ("Kıyma", 250), ("Soğan", 1), ("Yeşil biber", 2), ("Domates", 1), ("Tereyağı", 1), ("Biber salçası", 1), ("Tuz", 1)],
        "recipe": "1. Un, maya, tuz ve ılık sudan hamur yoğurup 30 dakika mayalandırın.\n2. Kıymayı soğan, biber, domates, salça ve tuzla karıştırın.\n3. Hamuru oval açıp kenarlarını kıvırın, harcı içine yayın.\n4. 230 derece fırında 12-15 dakika pişirin.\n5. Üzerine tereyağı sürerek servis edin.",
    },
]
