MEALS = [
    # Kahvaltı
    {
        "name": "Menemen",
        "desc": "Domates, biber ve yumurtayla yapılan kahvaltılık.",
        "region": "turkiye", "categories": ["kahvalti"],
        "prep": 5, "cook": 10, "servings": 2, "cost": 60,
        "nutrition": (280, 16, 10, 20, 2),
        "ingredients": [("Yumurta", 4), ("Domates", 3), ("Yeşil biber", 2), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Tereyağında doğranmış biberleri hafifçe kavurun.\n2. Soyulup doğranmış domatesleri ekleyip suyunu çekene kadar pişirin.\n3. Yumurtaları kırıp tuzlayın.\n4. İstediğiniz kıvama gelene kadar hafifçe karıştırarak pişirip sıcak servis edin.",
    },
    {
        "name": "Sucuklu Yumurta",
        "desc": "Tavada kızaran sucuk ve gözleme yumurta.",
        "region": "turkiye", "categories": ["kahvalti"],
        "prep": 5, "cook": 10, "servings": 2, "cost": 150,
        "nutrition": (450, 28, 4, 35, 0),
        "ingredients": [("Yumurta", 4), ("Sucuk", 150)],
        "recipe": "1. Sucuğu halka doğrayıp yağsız tavada iki yüzünü de kızartın.\n2. Yumurtaları sucukların üzerine kırın.\n3. Kapağı kapatıp beyazı tutana kadar pişirin.\n4. Sıcak servis edin.",
    },
    {
        "name": "Kaşarlı Omlet",
        "desc": "Kaşar peynirli yumuşacık omlet.",
        "region": "turkiye", "categories": ["kahvalti"],
        "prep": 5, "cook": 8, "servings": 2, "cost": 80,
        "nutrition": (330, 24, 3, 25, 0),
        "ingredients": [("Yumurta", 4), ("Kaşar peyniri", 80), ("Süt", 50), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Yumurta, süt ve tuzu çırpın.\n2. Tereyağını tavada eritip karışımı dökün.\n3. Yarı pişince üzerine rendelenmiş kaşarı serpin.\n4. İkiye katlayıp peynir eriyene kadar pişirin.",
    },
    {
        "name": "Kuymak (Mıhlama)",
        "desc": "Mısır unu ve peynirle yapılan tel tel uzayan Karadeniz kahvaltısı.",
        "region": "karadeniz", "categories": ["kahvalti"],
        "prep": 5, "cook": 15, "servings": 2, "cost": 130,
        "nutrition": (620, 25, 38, 40, 2),
        "ingredients": [("Mısır unu", 60), ("Tereyağı", 3), ("Kaşar peyniri", 200)],
        "recipe": "1. Tereyağını tavada eritin, mısır ununu ekleyip kokusu çıkana kadar kavurun.\n2. Yarım su bardağı sıcak su ekleyip karıştırın.\n3. Rendelenmiş peyniri ilave edip tel tel uzayana kadar karıştırın.\n4. Sıcak sıcak ekmekle servis edin.",
    },
    {
        "name": "Çılbır",
        "desc": "Sarımsaklı yoğurt üzerinde poşe yumurta, tereyağlı pul biber.",
        "region": "ic-anadolu", "categories": ["kahvalti"],
        "prep": 5, "cook": 10, "servings": 2, "cost": 90,
        "nutrition": (380, 22, 8, 29, 0),
        "ingredients": [("Yumurta", 4), ("Yoğurt", 300), ("Sarımsak", 2), ("Tereyağı", 2), ("Pul biber", 1), ("Sirke", 1)],
        "recipe": "1. Yoğurdu ezilmiş sarımsakla karıştırıp tabaklara paylaştırın.\n2. Kaynayan suya sirke ekleyip yumurtaları tek tek kırarak 3 dakika poşe edin.\n3. Yumurtaları yoğurdun üzerine yerleştirin.\n4. Tereyağında pul biberi kızdırıp üzerine gezdirin.",
    },
    {
        "name": "Patatesli Yumurta",
        "desc": "Kızarmış patates küpleri üzerine kırılan doyurucu kahvaltılık.",
        "region": "turkiye", "categories": ["kahvalti"],
        "prep": 10, "cook": 15, "servings": 2, "cost": 70,
        "nutrition": (350, 14, 22, 22, 2),
        "ingredients": [("Patates", 2), ("Yumurta", 4), ("Soğan", 1), ("Sıvı yağ", 2), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Patatesleri küçük küpler halinde doğrayın.\n2. Kızgın yağda patatesleri ve ince doğranmış soğanı kızarana kadar kavurun.\n3. Üzerine yumurtaları kırın, tuz ve karabiber serpin.\n4. Yumurta akı pişip sarısı istediğiniz kıvama gelene kadar kısık ateşte pişirin.",
    },
    {
        "name": "Pişi",
        "desc": "Kızgın yağda kabaran hamur; peynir ve reçelle.",
        "region": "marmara", "categories": ["kahvalti", "hamur-isi"],
        "prep": 60, "cook": 20, "servings": 4, "cost": 70,
        "nutrition": (350, 8, 50, 14, 2),
        "ingredients": [("Un", 300), ("Kuru maya", 1), ("Şeker", 5), ("Tuz", 1), ("Sıvı yağ", 6)],
        "recipe": "1. Un, maya, şeker, tuz ve ılık sudan hamur yoğurup 45 dakika mayalandırın.\n2. Hamuru parçalara ayırıp elle yassıltın.\n3. Kızgın yağda iki yüzünü de kabarıp kızarana kadar kızartın.\n4. Sıcak servis edin.",
    },
    {
        "name": "Poğaça",
        "desc": "Peynirli, maydanozlu yumuşak poğaça.",
        "region": "marmara", "categories": ["kahvalti", "hamur-isi"],
        "prep": 30, "cook": 25, "servings": 6, "cost": 110,
        "nutrition": (480, 14, 52, 24, 2),
        "ingredients": [("Un", 400), ("Yoğurt", 100), ("Sıvı yağ", 6), ("Yumurta", 1), ("Kabartma tozu", 2), ("Beyaz peynir", 150), ("Maydanoz", 1), ("Tuz", 1)],
        "recipe": "1. Un, yoğurt, yağ, yumurta, kabartma tozu ve tuzla yumuşak bir hamur yoğurun.\n2. Peyniri maydanozla karıştırıp iç harcı hazırlayın.\n3. Hamurdan parçalar alıp açın, içine harç koyun ve kapatın.\n4. Üzerine yumurta sürüp 180 derece fırında 25 dakika pişirin.",
    },
    # Salata
    {
        "name": "Çoban Salata",
        "desc": "Domates, salatalık ve biberle yapılan klasik salata.",
        "region": "turkiye", "categories": ["salata"],
        "prep": 10, "cook": 0, "servings": 4, "cost": 40,
        "nutrition": (90, 2, 8, 6, 3),
        "ingredients": [("Domates", 3), ("Salatalık", 2), ("Yeşil biber", 2), ("Soğan", 1), ("Maydanoz", 0.5), ("Zeytinyağı", 2), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Tüm sebzeleri küçük küp doğrayın.\n2. Kıyılmış maydanozu ekleyin.\n3. Zeytinyağı, limon suyu ve tuzla karıştırıp hemen servis edin.",
    },
    {
        "name": "Gavurdağı Salatası",
        "desc": "Cevizli, nar ekşili Antep salatası.",
        "region": "guneydogu", "categories": ["salata"],
        "prep": 15, "cook": 0, "servings": 4, "cost": 70,
        "nutrition": (170, 3, 10, 13, 3),
        "ingredients": [("Domates", 3), ("Salatalık", 1), ("Soğan", 1), ("Ceviz", 40), ("Nar ekşisi", 2), ("Zeytinyağı", 2), ("Maydanoz", 1), ("Tuz", 1), ("Pul biber", 0.5)],
        "recipe": "1. Domates, salatalık ve soğanı ince küp doğrayın.\n2. Kıyılmış maydanoz ve ceviz ekleyin.\n3. Nar ekşisi, zeytinyağı, tuz ve pul biberle karıştırıp servis edin.",
    },
    {
        "name": "Mevsim Salata",
        "desc": "Marul, roka, havuç ve salatalıklı hafif salata.",
        "region": "turkiye", "categories": ["salata"],
        "prep": 10, "cook": 0, "servings": 4, "cost": 50,
        "nutrition": (80, 2, 8, 5, 3),
        "ingredients": [("Marul", 1), ("Roka", 1), ("Salatalık", 2), ("Domates", 2), ("Havuç", 1), ("Zeytinyağı", 2), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Marul ve rokayı yıkayıp doğrayın.\n2. Salatalık, domates ve rendelenmiş havucu ekleyin.\n3. Zeytinyağı, limon ve tuzla karıştırıp servis edin.",
    },
    {
        "name": "Piyaz",
        "desc": "Antalya usulü tahinli, yumurtalı fasulye piyazı.",
        "region": "akdeniz", "categories": ["salata", "baklagil"],
        "prep": 20, "cook": 0, "servings": 4, "cost": 80,
        "nutrition": (260, 13, 28, 11, 9),
        "ingredients": [("Kuru fasulye", 200), ("Soğan", 1), ("Maydanoz", 1), ("Domates", 2), ("Yumurta", 2), ("Sirke", 2), ("Zeytinyağı", 3), ("Tahin", 1), ("Tuz", 1), ("Sumak", 1)],
        "recipe": "1. Fasulyeyi ıslatıp haşlayın, soğutun.\n2. Soğanı sumakla ovup yıkayın, maydanozu kıyın.\n3. Fasulye, soğan, domates ve maydanozu karıştırın.\n4. Zeytinyağı, sirke, tahin ve tuzu çırpıp üzerine dökün.\n5. Haşlanmış yumurta dilimleriyle süsleyin.",
    },
    {
        "name": "Kısır",
        "desc": "İnce bulgurlu, nar ekşili baharatlı kısır.",
        "region": "guneydogu", "categories": ["salata"],
        "prep": 25, "cook": 0, "servings": 4, "cost": 70,
        "nutrition": (250, 6, 42, 7, 6),
        "ingredients": [("İnce bulgur", 200), ("Domates", 2), ("Salatalık", 1), ("Taze soğan", 1), ("Maydanoz", 1), ("Nar ekşisi", 2), ("Biber salçası", 1), ("Salça", 1), ("Zeytinyağı", 3), ("Limon", 1), ("Tuz", 1), ("Pul biber", 1)],
        "recipe": "1. İnce bulguru 1 su bardağı sıcak suyla ıslatıp 15 dakika bekletin.\n2. Salçaları, zeytinyağını ve baharatları ekleyip yoğurun.\n3. İnce doğranmış domates, salatalık, taze soğan ve maydanozu katın.\n4. Nar ekşisi ve limonla tatlandırın; marul yapraklarıyla servis edin.",
    },
    {
        "name": "Patates Salatası",
        "desc": "Haşlanmış patates, taze soğan ve maydanozla.",
        "region": "turkiye", "categories": ["salata"],
        "prep": 15, "cook": 20, "servings": 4, "cost": 60,
        "nutrition": (220, 4, 32, 9, 3),
        "ingredients": [("Patates", 4), ("Taze soğan", 1), ("Maydanoz", 1), ("Zeytinyağı", 3), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Patatesleri haşlayıp kabuklarını soyun ve küp doğrayın.\n2. Taze soğan ve maydanozu ince kıyıp ekleyin.\n3. Zeytinyağı, limon ve tuzla karıştırın.\n4. Ilık veya soğuk servis edin.",
    },
    {
        "name": "Cacık",
        "desc": "Salatalıklı, naneli yoğurt; pilavın ve kızartmanın yoldaşı.",
        "region": "turkiye", "categories": ["salata", "yan-yemek"],
        "prep": 10, "cook": 0, "servings": 4, "cost": 50,
        "nutrition": (110, 7, 9, 5, 1),
        "ingredients": [("Yoğurt", 400), ("Salatalık", 2), ("Sarımsak", 2), ("Kuru nane", 1), ("Zeytinyağı", 1), ("Tuz", 1)],
        "recipe": "1. Salatalıkları rendeleyin veya ince doğrayın.\n2. Yoğurdu ezilmiş sarımsak ve tuzla çırpın, gerekirse biraz su ekleyip açın.\n3. Salatalığı ekleyip karıştırın.\n4. Zeytinyağı ve nane ile servis edin.",
    },
    {
        "name": "Börülce Salatası",
        "desc": "Limonlu, zeytinyağlı kuru börülce salatası.",
        "region": "ege", "categories": ["salata", "baklagil"],
        "prep": 15, "cook": 40, "servings": 4, "cost": 70,
        "nutrition": (230, 10, 28, 9, 8),
        "ingredients": [("Kuru börülce", 200), ("Taze soğan", 1), ("Maydanoz", 1), ("Zeytinyağı", 3), ("Limon", 1), ("Sarımsak", 1), ("Tuz", 1)],
        "recipe": "1. Börülceyi ıslatıp yumuşayana kadar haşlayın, süzüp soğutun.\n2. İnce doğranmış taze soğan, maydanoz ve ezilmiş sarımsağı ekleyin.\n3. Zeytinyağı, limon ve tuzla karıştırıp servis edin.",
    },
    {
        "name": "Ezme",
        "desc": "Acılı domates, biber ve soğan ezmesi.",
        "region": "guneydogu", "categories": ["salata"],
        "prep": 15, "cook": 0, "servings": 4, "cost": 50,
        "nutrition": (100, 2, 10, 6, 3),
        "ingredients": [("Domates", 3), ("Soğan", 1), ("Yeşil biber", 2), ("Maydanoz", 1), ("Biber salçası", 1), ("Nar ekşisi", 2), ("Zeytinyağı", 2), ("Pul biber", 1), ("Tuz", 1)],
        "recipe": "1. Domates, soğan, biber ve maydanozu çok ince kıyın.\n2. Biber salçası, nar ekşisi, zeytinyağı ve baharatları ekleyip karıştırın.\n3. En az 15 dakika dinlendirip servis edin.",
    },
    # Tatlı
    {
        "name": "Sütlaç",
        "desc": "Fırınlanmış geleneksel sütlü tatlı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 10, "cook": 40, "servings": 6, "cost": 80,
        "nutrition": (230, 6, 40, 5, 0),
        "ingredients": [("Süt", 1000), ("Pirinç", 100), ("Şeker", 150), ("Nişasta", 20), ("Vanilya", 1)],
        "recipe": "1. Pirinci 2 su bardağı suda yumuşayana kadar haşlayın.\n2. Sütü ve şekeri ekleyip kaynatın.\n3. Az soğuk sütte açtığınız nişastayı ilave edip kıvam alana kadar karıştırın, vanilya katın.\n4. Kaselere paylaştırıp soğutun, isterseniz fırında üzerini kızartın.",
    },
    {
        "name": "Kazandibi",
        "desc": "Tabanı karamelize edilen, hafif yanık tadıyla sevilen muhallebi tatlısı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 10, "cook": 30, "servings": 6, "cost": 90,
        "nutrition": (240, 6, 42, 6, 0),
        "ingredients": [("Süt", 1000), ("Şeker", 200), ("Nişasta", 50), ("Tereyağı", 1), ("Vanilya", 1)],
        "recipe": "1. Sütü, şekeri ve nişastayı karıştırıp sürekli karıştırarak koyulaşana kadar pişirin.\n2. Tereyağı sürülmüş tavaya şeker serpip karamelize edin.\n3. Muhallebiyi tavaya dökün ve altı kızarana kadar 5 dakika pişirin.\n4. Soğutup dilimleyin, kızarmış yüzü üste gelecek şekilde katlayarak servis edin.",
    },
    {
        "name": "İrmik Helvası",
        "desc": "Tereyağında kavrulmuş irmikten sütlü helva.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 10, "cook": 25, "servings": 6, "cost": 100,
        "nutrition": (330, 5, 48, 13, 1),
        "ingredients": [("İrmik", 200), ("Tereyağı", 4), ("Süt", 500), ("Şeker", 150), ("Çam fıstığı", 20)],
        "recipe": "1. Tereyağında çam fıstığını ve irmiği kısık ateşte kokusu çıkana kadar kavurun.\n2. Süt ve şekeri ayrı bir tencerede kaynatın.\n3. Sıcak sütü irmiğe azar azar ekleyip karıştırın.\n4. Kapağını kapatıp 10 dakika demlendirin, servis edin.",
    },
    {
        "name": "Revani",
        "desc": "İrmikli, şerbetli klasik tatlı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 20, "cook": 35, "servings": 8, "cost": 110,
        "nutrition": (330, 5, 58, 9, 1),
        "ingredients": [("İrmik", 150), ("Un", 100), ("Yumurta", 3), ("Şeker", 400), ("Yoğurt", 150), ("Kabartma tozu", 2), ("Limon", 1), ("Sıvı yağ", 6)],
        "recipe": "1. Yumurta ve 150 g şekeri köpürene kadar çırpın.\n2. Yoğurt, yağ, irmik, un ve kabartma tozunu ekleyip karıştırın.\n3. Yağlı tepsiye dökün ve 180 derecede 30-35 dakika pişirin.\n4. 250 g şeker, 2 su bardağı su ve limon suyuyla şerbeti kaynatıp soğutun.\n5. Sıcak revaniye soğuk şerbeti dökün, bekleyip dilimleyin.",
    },
    {
        "name": "Şekerpare",
        "desc": "Fındıklı, şerbetli yumuşak Marmara tatlısı.",
        "region": "marmara", "categories": ["tatli"],
        "prep": 30, "cook": 30, "servings": 8, "cost": 100,
        "nutrition": (300, 4, 48, 11, 1),
        "ingredients": [("Un", 200), ("İrmik", 100), ("Tereyağı", 6), ("Yumurta", 1), ("Şeker", 300), ("Fındık", 20)],
        "recipe": "1. Un, irmik, yumuşak tereyağı ve yumurtayı yoğurup hamur hazırlayın.\n2. Ceviz büyüklüğünde parçalar alıp yassıltın, ortasına birer fındık koyun.\n3. Tepsiye dizip 180 derece fırında 25-30 dakika pişirin.\n4. Şeker ve 2 su bardağı suyla şerbet yapıp soğutun, sıcak tatlının üzerine dökün.",
    },
    {
        "name": "Kabak Tatlısı",
        "desc": "Cevizli, tahinli bal kabağı tatlısı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 15, "cook": 40, "servings": 6, "cost": 90,
        "nutrition": (220, 3, 45, 4, 4),
        "ingredients": [("Bal kabağı", 1000), ("Şeker", 250), ("Ceviz", 60), ("Tarçın", 1), ("Tahin", 2)],
        "recipe": "1. Kabağı dilimleyip kabuklu yüzü altta kalacak şekilde tencereye dizin.\n2. Aralarına şeker serpip bir gece bekletin.\n3. Kapağı kapalı kısık ateşte kabaklar yumuşayana kadar 35-40 dakika pişirin.\n4. Soğutun, ceviz ve tahinle servis edin, tarçın serpin.",
    },
    {
        "name": "Aşure",
        "desc": "Buğday, baklagil ve kuruyemişle yapılan bereket tatlısı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 30, "cook": 90, "servings": 10, "cost": 220,
        "nutrition": (300, 6, 55, 7, 6),
        "ingredients": [("Aşurelik buğday", 150), ("Nohut", 50), ("Kuru fasulye", 50), ("Şeker", 300), ("Kuru kayısı", 60), ("Kuru üzüm", 60), ("Ceviz", 50), ("Fındık", 40), ("Tarçın", 1)],
        "recipe": "1. Buğday, nohut ve fasulyeyi bir gece ıslatıp ayrı ayrı haşlayın.\n2. Buğdayı kaynatıp yumuşayınca nohut ve fasulyeyi ekleyin.\n3. Doğranmış kayısı ve kuru üzümü ilave edin.\n4. Şekeri katıp 30 dakika daha pişirin.\n5. Kaselere alıp soğutun, ceviz, fındık ve tarçınla süsleyin.",
    },
    {
        "name": "Künefe",
        "desc": "Kadayıf ve peynirle yapılan, sıcak şerbetli Hatay tatlısı.",
        "region": "akdeniz", "categories": ["tatli"],
        "prep": 30, "cook": 20, "servings": 4, "cost": 250,
        "nutrition": (620, 16, 70, 32, 1),
        "ingredients": [("Kadayıf", 250), ("Hellim peyniri", 250), ("Tereyağı", 4), ("Şeker", 300), ("Antep fıstığı", 30)],
        "recipe": "1. Kadayıfı ince kıyıp erimiş tereyağıyla ovun.\n2. Yağlı tavanın yarısına kadayıfı bastırın, peyniri yayın, kalan kadayıfla kapatın.\n3. Orta ateşte iki yüzünü de altın rengi olana kadar pişirin.\n4. Şeker ve 1,5 su bardağı sudan hazırlanmış şerbeti dökün.\n5. Antep fıstığı serpip sıcak servis edin.",
    },
    {
        "name": "Baklava",
        "desc": "Kat kat yufkalı, cevizli veya fıstıklı şerbetli tatlı.",
        "region": "guneydogu", "categories": ["tatli"],
        "prep": 60, "cook": 40, "servings": 12, "cost": 500,
        "nutrition": (420, 6, 50, 22, 2),
        "ingredients": [("Yufka", 10), ("Tereyağı", 6), ("Ceviz", 200), ("Şeker", 400), ("Limon", 1)],
        "recipe": "1. Yufkaların her birini eritilmiş tereyağıyla yağlayıp tepsiye 5 kat dizin.\n2. Cevizi iri çekip üzerine serpin, kalan yufkalarla kapatın.\n3. Baklava dilimi şeklinde kesip üzerine tereyağı gezdirin.\n4. 180 derece fırında 35-40 dakika pişirin.\n5. Şeker, 2 su bardağı su ve limonla şerbeti kaynatıp soğutun, sıcak baklavaya dökün.",
    },
    {
        "name": "Ayva Tatlısı",
        "desc": "Kaymakla servis edilen, şurupta pişmiş ayva.",
        "region": "marmara", "categories": ["tatli"],
        "prep": 15, "cook": 60, "servings": 4, "cost": 100,
        "nutrition": (280, 3, 52, 8, 5),
        "ingredients": [("Ayva", 4), ("Şeker", 200), ("Kaymak", 100), ("Ceviz", 40)],
        "recipe": "1. Ayvaları soyup ikiye bölün, çekirdeklerini çıkarın.\n2. Tencereye dizip şekeri serpin, 2 su bardağı su ekleyin.\n3. Kapağı kapalı kısık ateşte ayvalar kızıl renk alıp yumuşayana kadar 1 saat pişirin.\n4. Soğutup kaymak ve cevizle servis edin.",
    },
    {
        "name": "Laz Böreği",
        "desc": "Muhallebi dolgulu, tereyağlı Karadeniz tatlısı.",
        "region": "karadeniz", "categories": ["tatli"],
        "prep": 40, "cook": 20, "servings": 6, "cost": 130,
        "nutrition": (330, 6, 44, 14, 1),
        "ingredients": [("Yufka", 6), ("Süt", 500), ("Nişasta", 40), ("Şeker", 100), ("Tereyağı", 3), ("Pudra şekeri", 30)],
        "recipe": "1. Süt, şeker ve nişastayı karıştırıp koyulaşana kadar pişirin, soğutun.\n2. Yufkaları kare kesip aralarını tereyağıyla yağlayarak 3-4 kat üst üste koyun.\n3. Ortasına muhallebi koyup zarf gibi katlayın.\n4. Yağlı tepside veya tavada iki yüzünü de altın rengi olana kadar pişirin.\n5. Pudra şekeri serpin.",
    },
    {
        "name": "Muhallebi",
        "desc": "Vanilyalı, hafif sütlü tatlı.",
        "region": "turkiye", "categories": ["tatli"],
        "prep": 5, "cook": 15, "servings": 6, "cost": 70,
        "nutrition": (190, 5, 34, 3, 0),
        "ingredients": [("Süt", 1000), ("Şeker", 150), ("Nişasta", 60), ("Vanilya", 1), ("Tarçın", 0.5)],
        "recipe": "1. Nişastayı az soğuk sütte açın.\n2. Kalan süt ve şekerle karıştırıp sürekli karıştırarak koyulaşana kadar pişirin.\n3. Vanilyayı ekleyin.\n4. Kaselere paylaştırıp soğutun, üzerine tarçın serpin.",
    },
]
