MEALS = [
    {
        "name": "Pirinç Pilavı",
        "desc": "Tereyağlı, dökülür klasik pirinç pilavı.",
        "region": "turkiye", "categories": ["pilav-makarna", "yan-yemek"],
        "prep": 5, "cook": 20, "servings": 4, "cost": 60,
        "nutrition": (250, 5, 50, 4, 1),
        "ingredients": [("Pirinç", 300), ("Tereyağı", 2), ("Tuz", 1)],
        "recipe": "1. Pirinci ılık tuzlu suda 20 dakika bekletip yıkayın.\n2. Tereyağında pirinci saydam olana kadar kavurun.\n3. 3 su bardağı sıcak su ve tuzu ekleyin.\n4. Kapağı kapalı kısık ateşte suyunu çekene kadar 15 dakika pişirin, 10 dakika demlendirin.",
    },
    {
        "name": "Bulgur Pilavı",
        "desc": "Soğanlı, salçalı bulgur pilavı.",
        "region": "turkiye", "categories": ["pilav-makarna", "yan-yemek"],
        "prep": 5, "cook": 20, "servings": 4, "cost": 50,
        "nutrition": (240, 8, 46, 4, 7),
        "ingredients": [("Bulgur", 300), ("Soğan", 1), ("Tereyağı", 1), ("Salça", 1), ("Tuz", 1)],
        "recipe": "1. Tereyağında ince doğranmış soğanı kavurun, salçayı ekleyin.\n2. Bulguru ilave edip 2 dakika çevirin.\n3. 3 su bardağı sıcak su ve tuz ekleyin.\n4. Kısık ateşte suyunu çekene kadar pişirip 10 dakika demlendirin.",
    },
    {
        "name": "Şehriyeli Pilav",
        "desc": "Tel şehriyeli tereyağlı pirinç pilavı.",
        "region": "turkiye", "categories": ["pilav-makarna", "yan-yemek"],
        "prep": 5, "cook": 20, "servings": 4, "cost": 70,
        "nutrition": (280, 6, 52, 5, 2),
        "ingredients": [("Pirinç", 250), ("Şehriye", 60), ("Tereyağı", 2), ("Tuz", 1)],
        "recipe": "1. Tereyağında şehriyeyi kızarana kadar kavurun.\n2. Yıkanmış pirinci ekleyip birkaç dakika çevirin.\n3. 3 su bardağı sıcak su ve tuzu ekleyin.\n4. Kısık ateşte 15 dakika pişirip 10 dakika demlendirin.",
    },
    {
        "name": "Domatesli Bulgur Pilavı",
        "desc": "Domates ve biberli bulgur pilavı.",
        "region": "turkiye", "categories": ["pilav-makarna", "yan-yemek"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 60,
        "nutrition": (250, 8, 46, 5, 8),
        "ingredients": [("Bulgur", 300), ("Domates", 2), ("Soğan", 1), ("Yeşil biber", 1), ("Salça", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Tereyağında soğanı ve biberi kavurun, salçayı ekleyin.\n2. Rendelenmiş domatesi ekleyip birkaç dakika pişirin.\n3. Bulguru ve 3 su bardağı sıcak suyu ilave edin, tuzlayın.\n4. Kısık ateşte suyunu çekene kadar pişirip demlendirin.",
    },
    {
        "name": "Nohutlu Pilav",
        "desc": "Haşlanmış nohutlu pirinç pilavı.",
        "region": "turkiye", "categories": ["pilav-makarna", "yan-yemek", "baklagil"],
        "prep": 10, "cook": 25, "servings": 4, "cost": 90,
        "nutrition": (330, 9, 58, 6, 4),
        "ingredients": [("Pirinç", 250), ("Nohut", 100), ("Tereyağı", 2), ("Tuz", 1)],
        "recipe": "1. Nohutu ıslatıp yumuşayana kadar haşlayın.\n2. Tereyağında pirinci kavurun.\n3. Nohutu ve 3 su bardağı sıcak su ile tuzu ekleyin.\n4. Kısık ateşte suyunu çekene kadar pişirip demlendirin.",
    },
    {
        "name": "Sebzeli Makarna",
        "desc": "Kabak, havuç ve domatesli makarna.",
        "region": "turkiye", "categories": ["pilav-makarna", "sebze"],
        "prep": 10, "cook": 15, "servings": 4, "cost": 70,
        "nutrition": (380, 12, 68, 7, 4),
        "ingredients": [("Makarna", 300), ("Kabak", 1), ("Domates", 2), ("Havuç", 1), ("Zeytinyağı", 2), ("Tuz", 1)],
        "recipe": "1. Makarnayı tuzlu suda haşlayıp süzün.\n2. Zeytinyağında doğranmış kabak ve havucu birkaç dakika çevirin.\n3. Rendelenmiş domatesi ekleyip 5 dakika pişirin.\n4. Makarnayı sebzelerle karıştırıp servis edin.",
    },
    {
        "name": "Fırında Makarna",
        "desc": "Kıymalı, beşamelli, kaşarlı fırın makarna.",
        "region": "turkiye", "categories": ["pilav-makarna", "et"],
        "prep": 25, "cook": 30, "servings": 4, "cost": 200,
        "nutrition": (500, 24, 55, 20, 3),
        "ingredients": [("Makarna", 300), ("Kıyma", 150), ("Süt", 250), ("Yumurta", 2), ("Kaşar peyniri", 100), ("Tereyağı", 1), ("Un", 20), ("Tuz", 1)],
        "recipe": "1. Makarnayı haşlayıp süzün, yağda kavrulmuş kıymayla karıştırın.\n2. Tereyağında unu kavurup sütü ekleyerek beşamel sos yapın.\n3. Sosu çırpılmış yumurta ile birleştirin.\n4. Makarnayı tepsiye alıp sosu dökün, üzerine rendelenmiş kaşar serpin.\n5. 200 derece fırında 25 dakika pişirin.",
    },
    {
        "name": "Kıymalı Makarna",
        "desc": "Domates soslu, kıymalı spagetti.",
        "region": "turkiye", "categories": ["pilav-makarna", "et"],
        "prep": 10, "cook": 25, "servings": 4, "cost": 190,
        "nutrition": (470, 24, 58, 14, 3),
        "ingredients": [("Spagetti", 300), ("Kıyma", 200), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Sıvı yağ", 1), ("Tuz", 1)],
        "recipe": "1. Yağda soğanı ve kıymayı suyunu çekene kadar kavurun.\n2. Salça ve rendelenmiş domatesi ekleyip 15 dakika pişirin, tuzlayın.\n3. Spagettiyi haşlayıp süzün.\n4. Sosu makarnanın üzerine dökerek servis edin.",
    },
    {
        "name": "Su Böreği",
        "desc": "Haşlanmış yufkalı, peynirli, tereyağlı klasik su böreği.",
        "region": "marmara", "categories": ["hamur-isi"],
        "prep": 60, "cook": 40, "servings": 6, "cost": 200,
        "nutrition": (520, 20, 48, 28, 2),
        "ingredients": [("Un", 400), ("Yumurta", 4), ("Beyaz peynir", 250), ("Maydanoz", 1), ("Süt", 250), ("Tereyağı", 3), ("Sıvı yağ", 4), ("Tuz", 1)],
        "recipe": "1. Un, 2 yumurta ve tuzla hamur yoğurup bezelere ayırın, ince açın.\n2. Yufkaları kaynar tuzlu suda haşlayıp soğuk suya alın.\n3. Yağlanmış tepsiye yufkaları kat kat dizin, aralarına peynir ve maydanoz serpin.\n4. Süt, yağ ve kalan yumurtayı çırpıp üzerine dökün.\n5. 190 derece fırında 40 dakika pişirin.",
    },
    {
        "name": "Peynirli Gözleme",
        "desc": "El açması, peynirli ve maydanozlu gözleme.",
        "region": "turkiye", "categories": ["hamur-isi"],
        "prep": 30, "cook": 20, "servings": 4, "cost": 120,
        "nutrition": (430, 15, 58, 16, 2),
        "ingredients": [("Un", 400), ("Beyaz peynir", 200), ("Maydanoz", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Un, tuz ve ılık sudan hamur yoğurup dinlendirin.\n2. Bezelere ayırıp ince açın.\n3. Yarısına ezilmiş peynir ve maydanoz koyup katlayın.\n4. Sıcak sacda veya tavada iki yüzünü de pişirin.\n5. Üzerine tereyağı sürüp servis edin.",
    },
    {
        "name": "Ispanaklı Börek",
        "desc": "Ispanaklı, peynirli yufka böreği.",
        "region": "turkiye", "categories": ["hamur-isi", "sebze"],
        "prep": 30, "cook": 40, "servings": 6, "cost": 180,
        "nutrition": (450, 18, 42, 24, 4),
        "ingredients": [("Yufka", 4), ("Ispanak", 500), ("Beyaz peynir", 200), ("Yumurta", 2), ("Süt", 200), ("Sıvı yağ", 4), ("Soğan", 1), ("Tuz", 1)],
        "recipe": "1. Soğanı yağda kavurup doğranmış ıspanağı suyunu çekene kadar pişirin, soğutup ezilmiş peynirle karıştırın.\n2. Yağlanmış tepsiye 2 yufka serin, harcı yayın, kalan yufkaları üstüne koyun.\n3. Yumurta, süt ve yağı çırpıp üzerine gezdirin.\n4. 190 derece fırında 35-40 dakika pişirin.",
    },
    {
        "name": "Sigara Böreği",
        "desc": "Peynirli, maydanozlu çıtır sigara böreği.",
        "region": "turkiye", "categories": ["hamur-isi"],
        "prep": 30, "cook": 15, "servings": 4, "cost": 180,
        "nutrition": (420, 16, 32, 26, 2),
        "ingredients": [("Yufka", 4), ("Beyaz peynir", 250), ("Maydanoz", 1), ("Yumurta", 1), ("Sıvı yağ", 6)],
        "recipe": "1. Peyniri ezip maydanoz ve yumurta ile karıştırın.\n2. Yufkaları üçgen kesip geniş ucuna harç koyun.\n3. Kenarları içe katlayıp sigara şeklinde sarın, ucunu suyla yapıştırın.\n4. Kızgın yağda altın rengi olana kadar kızartın.",
    },
]
