MEALS = [
    {
        "name": "Zeytinyağlı Taze Fasulye",
        "desc": "Domatesli, soğanlı klasik zeytinyağlı; soğuk servis edilir.",
        "region": "ege", "categories": ["sebze"],
        "prep": 15, "cook": 40, "servings": 4, "cost": 110,
        "nutrition": (150, 4, 14, 9, 5),
        "ingredients": [("Taze fasulye", 500), ("Soğan", 1), ("Domates", 2), ("Sarımsak", 2), ("Zeytinyağı", 4), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Fasulyelerin uçlarını ayıklayıp ikiye bölün.\n2. Zeytinyağında soğanı ve sarımsağı kavurun.\n3. Fasulyeleri, rendelenmiş domatesi, şekeri ve tuzu ekleyin.\n4. Yarım su bardağı su koyup kapağı kapalı kısık ateşte 35-40 dakika pişirin.\n5. Ilıdıktan sonra servis edin.",
    },
    {
        "name": "Etli Taze Fasulye",
        "desc": "Kuşbaşı etle pişen sulu taze fasulye yemeği.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 15, "cook": 50, "servings": 4, "cost": 320,
        "nutrition": (260, 20, 14, 14, 5),
        "ingredients": [("Taze fasulye", 500), ("Kuşbaşı et", 200), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Eti yağda suyunu çekene kadar kavurun, soğanı ekleyin.\n2. Salçayı ve rendelenmiş domatesi ilave edin.\n3. Ayıkladığınız fasulyeleri ekleyip 1 su bardağı sıcak su koyun.\n4. Kısık ateşte et ve fasulye yumuşayana kadar 40 dakika pişirin.\n5. Tuzunu ayarlayıp servis edin.",
    },
    {
        "name": "Zeytinyağlı Enginar",
        "desc": "Havuç ve patatesle pişen, limonlu Ege klasiği.",
        "region": "ege", "categories": ["sebze"],
        "prep": 25, "cook": 35, "servings": 4, "cost": 200,
        "nutrition": (170, 4, 16, 10, 8),
        "ingredients": [("Enginar", 4), ("Havuç", 2), ("Patates", 1), ("Limon", 1), ("Zeytinyağı", 4), ("Dereotu", 1), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Enginarların dış yapraklarını soyup içini temizleyin, limonlu suda bekletin.\n2. Tencereye enginarları, doğranmış havuç ve patatesi dizin.\n3. Zeytinyağı, şeker, tuz ve limon suyunu ekleyin, yarım su bardağı su koyun.\n4. Kısık ateşte 35 dakika pişirin.\n5. Soğuduktan sonra dereotuyla servis edin.",
    },
    {
        "name": "İmam Bayıldı",
        "desc": "Soğanlı, domatesli dolgusuyla zeytinyağlı patlıcan.",
        "region": "ege", "categories": ["sebze"],
        "prep": 30, "cook": 45, "servings": 4, "cost": 130,
        "nutrition": (190, 3, 16, 13, 6),
        "ingredients": [("Patlıcan", 4), ("Soğan", 3), ("Sarımsak", 4), ("Domates", 3), ("Yeşil biber", 2), ("Maydanoz", 0.5), ("Zeytinyağı", 5), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Patlıcanları alaca soyup yağda hafifçe kızartın, boydan yarın.\n2. Zeytinyağında soğanı, sarımsağı ve biberi kavurun; doğranmış domates, maydanoz, şeker ve tuzu ekleyip harcı hazırlayın.\n3. Harcı patlıcanların içine doldurun.\n4. Tencereye dizip yarım su bardağı su koyun.\n5. Kısık ateşte 40 dakika pişirin, soğuk servis edin.",
    },
    {
        "name": "Karnıyarık",
        "desc": "Kıymalı iç harçla doldurulmuş, kızartılmış patlıcan.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 25, "cook": 40, "servings": 4, "cost": 250,
        "nutrition": (340, 16, 20, 22, 6),
        "ingredients": [("Patlıcan", 4), ("Kıyma", 250), ("Soğan", 1), ("Domates", 2), ("Yeşil biber", 4), ("Salça", 1), ("Sıvı yağ", 4), ("Tuz", 1)],
        "recipe": "1. Patlıcanları alaca soyup yağda kızartın, ortasından yarın.\n2. Yağda soğanı, kıymayı ve salçayı kavurun; doğranmış domates ve biberin yarısını, tuzu ekleyip harcı pişirin.\n3. Harcı patlıcanların içine doldurun, üzerine birer dilim domates ve biber koyun.\n4. Tepsiye dizip yarım su bardağı su ekleyin.\n5. 180 derece fırında 30 dakika pişirin.",
    },
    {
        "name": "Patlıcan Musakka",
        "desc": "Kıymalı harçla katmanlı kızarmış patlıcan.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 25, "cook": 40, "servings": 4, "cost": 230,
        "nutrition": (300, 15, 16, 20, 5),
        "ingredients": [("Patlıcan", 3), ("Kıyma", 250), ("Soğan", 1), ("Domates", 3), ("Yeşil biber", 2), ("Sarımsak", 2), ("Sıvı yağ", 4), ("Tuz", 1)],
        "recipe": "1. Patlıcanları dilimleyip tuzlu suda bekletin, kurulayıp yağda kızartın.\n2. Soğanı, sarımsağı ve kıymayı kavurun, doğranmış biber ve domatesi ekleyip pişirin.\n3. Tepsiye patlıcan dilimlerini dizin, üzerine kıymalı harcı yayın.\n4. Üzerine domates dilimleri koyup yarım su bardağı su ekleyin.\n5. 180 derece fırında 25 dakika pişirin.",
    },
    {
        "name": "Kabak Mücver",
        "desc": "Peynirli, dereotlu kabak mücveri; kahvaltıya da yakışır.",
        "region": "ege", "categories": ["sebze"],
        "prep": 20, "cook": 20, "servings": 4, "cost": 120,
        "nutrition": (210, 10, 14, 12, 2),
        "ingredients": [("Kabak", 3), ("Yumurta", 2), ("Un", 60), ("Beyaz peynir", 100), ("Dereotu", 1), ("Taze soğan", 1), ("Sıvı yağ", 4), ("Tuz", 1)],
        "recipe": "1. Kabakları rendeleyip tuzla karıştırın, suyunu iyice sıkın.\n2. Yumurta, un, ezilmiş peynir, kıyılmış dereotu ve taze soğanı ekleyip karıştırın.\n3. Kızgın yağda kaşıkla dökerek iki yüzünü de kızartın.\n4. Kâğıt havluya alıp yoğurtla servis edin.",
    },
    {
        "name": "Kabak Dolması",
        "desc": "Kıymalı pirinçli iç harçla doldurulmuş sulu kabak dolması.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 40, "cook": 40, "servings": 4, "cost": 210,
        "nutrition": (280, 14, 26, 13, 3),
        "ingredients": [("Kabak", 6), ("Kıyma", 200), ("Pirinç", 60), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Maydanoz", 0.5), ("Zeytinyağı", 2), ("Tuz", 1)],
        "recipe": "1. Kabakların içini oyun.\n2. Kıyma, yıkanmış pirinç, rendelenmiş soğan, kıyılmış maydanoz, salça, zeytinyağı ve tuzu yoğurun.\n3. Harcı kabaklara yarısına kadar doldurun (pirinç şişer).\n4. Tencereye dizin, rendelenmiş domates ve 1,5 su bardağı sıcak su ekleyin.\n5. Kısık ateşte 40 dakika pişirin.",
    },
    {
        "name": "Biber Dolması",
        "desc": "Kıymalı pirinçli dolmalık biber.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 40, "cook": 45, "servings": 4, "cost": 230,
        "nutrition": (310, 15, 32, 13, 3),
        "ingredients": [("Dolmalık biber", 8), ("Kıyma", 200), ("Pirinç", 80), ("Soğan", 2), ("Domates", 2), ("Salça", 1), ("Maydanoz", 1), ("Zeytinyağı", 2), ("Tuz", 1)],
        "recipe": "1. Biberlerin sapını kesip çekirdeklerini çıkarın.\n2. Kıyma, pirinç, rendelenmiş soğan, maydanoz, salça, zeytinyağı ve tuzu yoğurun.\n3. Biberleri harçla doldurun.\n4. Tencereye dizip üzerine rendelenmiş domates ve 2 su bardağı sıcak su ekleyin.\n5. Kısık ateşte 45 dakika pişirin.",
    },
    {
        "name": "Zeytinyağlı Yaprak Sarma",
        "desc": "İç pirinçli, kuş üzümlü, limonlu Ege usulü yaprak sarma.",
        "region": "ege", "categories": ["sebze"],
        "prep": 60, "cook": 45, "servings": 4, "cost": 190,
        "nutrition": (290, 4, 38, 14, 3),
        "ingredients": [("Asma yaprağı", 250), ("Pirinç", 150), ("Soğan", 3), ("Zeytinyağı", 6), ("Dereotu", 1), ("Maydanoz", 1), ("Kuru nane", 1), ("Limon", 1), ("Şeker", 5), ("Tuz", 1), ("Karabiber", 1), ("Kuş üzümü", 20), ("Çam fıstığı", 15)],
        "recipe": "1. Yaprakları sıcak suda haşlayıp süzün.\n2. Zeytinyağında soğanı ve çam fıstığını kavurun, yıkanmış pirinci, kuş üzümünü ve baharatları ekleyip 5 dakika çevirin; kıyılmış otları ve su ekleyip suyunu çekene kadar pişirin.\n3. Harcı yaprakların içine koyup sıkıca sarın.\n4. Tencereye dizip zeytinyağı, limon suyu ve 1,5 su bardağı sıcak su ekleyin, üzerine tabak koyun.\n5. Kısık ateşte 45 dakika pişirip soğutarak servis edin.",
    },
    {
        "name": "Ispanak Yemeği",
        "desc": "Pirinçli, yoğurtla servis edilen ıspanak yemeği.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 15, "cook": 25, "servings": 4, "cost": 100,
        "nutrition": (150, 7, 16, 7, 5),
        "ingredients": [("Ispanak", 750), ("Soğan", 2), ("Pirinç", 50), ("Salça", 1), ("Zeytinyağı", 3), ("Yoğurt", 200), ("Tuz", 1)],
        "recipe": "1. Ispanağı yıkayıp doğrayın.\n2. Zeytinyağında soğanı kavurun, salçayı ekleyin.\n3. Ispanağı ekleyip suyunu salana kadar pişirin.\n4. Yıkanmış pirinci ve yarım su bardağı su ilave edip 15 dakika pişirin, tuzlayın.\n5. Yoğurtla servis edin.",
    },
    {
        "name": "Türlü",
        "desc": "Mevsim sebzelerinin domatesli güveç usulü yemeği.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 25, "cook": 40, "servings": 4, "cost": 130,
        "nutrition": (190, 4, 24, 9, 6),
        "ingredients": [("Patlıcan", 1), ("Kabak", 2), ("Patates", 2), ("Taze fasulye", 250), ("Yeşil biber", 3), ("Domates", 3), ("Soğan", 1), ("Sarımsak", 2), ("Zeytinyağı", 4), ("Tuz", 1)],
        "recipe": "1. Tüm sebzeleri iri doğrayın.\n2. Zeytinyağında soğan ve sarımsağı kavurun.\n3. Patates ve fasulyeyi ekleyip 5 dakika çevirin, ardından diğer sebzeleri ve doğranmış domatesi ilave edin.\n4. Tuzlayıp 1 su bardağı su koyun.\n5. Kısık ateşte sebzeler yumuşayana kadar 35 dakika pişirin.",
    },
    {
        "name": "Bamya Yemeği",
        "desc": "Limonlu, domatesli zeytinyağlı bamya.",
        "region": "marmara", "categories": ["sebze"],
        "prep": 20, "cook": 35, "servings": 4, "cost": 150,
        "nutrition": (140, 4, 14, 8, 5),
        "ingredients": [("Bamya", 500), ("Soğan", 1), ("Domates", 2), ("Limon", 1), ("Zeytinyağı", 3), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Bamyaların sapını konik biçimde temizleyin, limonlu suda bekletin.\n2. Zeytinyağında soğanı kavurun, doğranmış domatesi ekleyin.\n3. Bamyaları, şekeri, tuzu ve limon suyunu ilave edin.\n4. Yarım su bardağı su koyup kapağı kapalı kısık ateşte 30 dakika pişirin.",
    },
    {
        "name": "Karnabahar Yemeği",
        "desc": "Domatesli, havuçlu karnabahar yemeği.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 15, "cook": 30, "servings": 4, "cost": 100,
        "nutrition": (150, 5, 16, 8, 5),
        "ingredients": [("Karnabahar", 700), ("Soğan", 1), ("Domates", 2), ("Salça", 1), ("Havuç", 1), ("Patates", 1), ("Zeytinyağı", 3), ("Tuz", 1)],
        "recipe": "1. Karnabaharı çiçeklerine ayırıp yıkayın, havuç ve patatesi doğrayın.\n2. Zeytinyağında soğanı ve salçayı kavurun.\n3. Sebzeleri ve doğranmış domatesi ekleyip tuzlayın.\n4. 1 su bardağı su koyup yumuşayana kadar 25 dakika pişirin.",
    },
    {
        "name": "Zeytinyağlı Pırasa",
        "desc": "Havuç ve pirinçle pişen, hafif zeytinyağlı pırasa.",
        "region": "ege", "categories": ["sebze"],
        "prep": 15, "cook": 30, "servings": 4, "cost": 110,
        "nutrition": (160, 3, 20, 8, 4),
        "ingredients": [("Pırasa", 700), ("Havuç", 2), ("Pirinç", 40), ("Zeytinyağı", 4), ("Limon", 1), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Pırasayı yıkayıp 3 cm'lik parçalara, havucu yarım ay doğrayın.\n2. Zeytinyağında pırasa ve havucu birkaç dakika çevirin.\n3. Pirinci, şekeri, tuzu ve limon suyunu ekleyin.\n4. 1 su bardağı sıcak su koyup 25 dakika pişirin, soğuk servis edin.",
    },
    {
        "name": "Zeytinyağlı Kereviz",
        "desc": "Havuçlu, patatesli, limonlu Ege usulü kereviz yemeği.",
        "region": "ege", "categories": ["sebze"],
        "prep": 15, "cook": 35, "servings": 4, "cost": 110,
        "nutrition": (150, 2, 17, 9, 5),
        "ingredients": [("Kereviz", 700), ("Havuç", 2), ("Patates", 1), ("Limon", 1), ("Zeytinyağı", 4), ("Şeker", 5), ("Dereotu", 1), ("Tuz", 1)],
        "recipe": "1. Kerevizi soyup küp doğrayın, limonlu suda bekletin; havuç ve patatesi doğrayın.\n2. Zeytinyağında sebzeleri birkaç dakika çevirin.\n3. Şeker, tuz ve limon suyunu ekleyip 1 su bardağı sıcak su koyun.\n4. Kısık ateşte 30 dakika pişirin.\n5. Soğuduktan sonra dereotuyla servis edin.",
    },
    {
        "name": "Kapuska",
        "desc": "Karadeniz'in kıymalı, pirinçli lahana yemeği.",
        "region": "karadeniz", "categories": ["sebze", "et"],
        "prep": 15, "cook": 35, "servings": 4, "cost": 170,
        "nutrition": (220, 12, 18, 11, 5),
        "ingredients": [("Beyaz lahana", 700), ("Kıyma", 150), ("Soğan", 1), ("Salça", 1), ("Domates", 1), ("Pirinç", 40), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Lahanayı ince doğrayın.\n2. Yağda soğanı ve kıymayı kavurun, salçayı ve rendelenmiş domatesi ekleyin.\n3. Lahanayı ve yıkanmış pirinci ilave edin, tuzlayın.\n4. 1 su bardağı su ekleyip lahana yumuşayana kadar yaklaşık 30 dakika pişirin.",
    },
    {
        "name": "Karalahana Sarması",
        "desc": "Kıymalı pirinç harçlı Karadeniz usulü karalahana sarması.",
        "region": "karadeniz", "categories": ["sebze", "et"],
        "prep": 50, "cook": 50, "servings": 4, "cost": 200,
        "nutrition": (280, 14, 28, 12, 6),
        "ingredients": [("Kara lahana", 500), ("Kıyma", 200), ("Pirinç", 80), ("Soğan", 2), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Karalahana yapraklarını sıcak suda 3 dakika haşlayıp kalın damarlarını kesin.\n2. Kıyma, yıkanmış pirinç, rendelenmiş soğan, salça, yağ ve tuzu yoğurun.\n3. Harcı yapraklara koyup sıkıca sarın.\n4. Tencereye dizip 2 su bardağı sıcak su ekleyin, üzerine tabak koyun.\n5. Kısık ateşte 50 dakika pişirin.",
    },
    {
        "name": "Etli Patates Yemeği",
        "desc": "Kuşbaşı etli, domatesli sulu patates yemeği.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 15, "cook": 45, "servings": 4, "cost": 330,
        "nutrition": (350, 20, 34, 14, 4),
        "ingredients": [("Patates", 5), ("Kuşbaşı et", 250), ("Soğan", 1), ("Domates", 1), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Eti yağda suyunu çekene kadar kavurun, soğanı ve salçayı ekleyin.\n2. Rendelenmiş domates ve 2 su bardağı sıcak su koyup eti 20 dakika pişirin.\n3. Küp doğranmış patatesleri ekleyin, tuzlayın.\n4. Patatesler yumuşayana kadar 25 dakika pişirin.",
    },
    {
        "name": "Bezelye Yemeği",
        "desc": "Havuçlu, dereotlu zeytinyağlı bezelye.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 10, "cook": 30, "servings": 4, "cost": 130,
        "nutrition": (190, 8, 24, 7, 7),
        "ingredients": [("Bezelye", 500), ("Havuç", 2), ("Patates", 1), ("Soğan", 1), ("Zeytinyağı", 3), ("Dereotu", 1), ("Tuz", 1)],
        "recipe": "1. Soğanı, havucu ve patatesi doğrayın.\n2. Zeytinyağında soğanı kavurun, havuç ve patatesi ekleyin.\n3. Bezelyeyi ve tuzu ilave edip 1 su bardağı su koyun.\n4. 25 dakika pişirip dereotuyla servis edin.",
    },
    {
        "name": "Semizotu Yemeği",
        "desc": "Pirinçli, yoğurtla servis edilen hafif Ege yemeği.",
        "region": "ege", "categories": ["sebze"],
        "prep": 15, "cook": 25, "servings": 4, "cost": 90,
        "nutrition": (140, 4, 14, 8, 3),
        "ingredients": [("Semizotu", 3), ("Soğan", 1), ("Domates", 1), ("Pirinç", 40), ("Zeytinyağı", 3), ("Yoğurt", 200), ("Tuz", 1)],
        "recipe": "1. Semizotunu yıkayıp doğrayın.\n2. Zeytinyağında soğanı kavurun, doğranmış domatesi ekleyin.\n3. Semizotunu ve yıkanmış pirinci ilave edin, tuzlayın.\n4. Yarım su bardağı su koyup pirinç yumuşayana kadar 20 dakika pişirin.\n5. Yoğurtla servis edin.",
    },
    {
        "name": "Mantar Sote",
        "desc": "Sarımsaklı, tereyağlı hızlı mantar sote.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 10, "cook": 15, "servings": 4, "cost": 120,
        "nutrition": (110, 5, 8, 7, 2),
        "ingredients": [("Mantar", 500), ("Soğan", 1), ("Sarımsak", 2), ("Tereyağı", 1), ("Sıvı yağ", 1), ("Karabiber", 0.5), ("Tuz", 1)],
        "recipe": "1. Mantarları dilimleyin, soğanı ve sarımsağı ince doğrayın.\n2. Yağ ve tereyağını kızdırıp soğanı kavurun.\n3. Mantarları ekleyip yüksek ateşte suyunu çekene kadar sotelenin.\n4. Sarımsak, tuz ve karabiberi ekleyip 2 dakika daha çevirin.",
    },
    {
        "name": "Sebzeli Güveç",
        "desc": "Fırında pişen, üzeri kaşarlı karışık sebze güveci.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 25, "cook": 45, "servings": 4, "cost": 150,
        "nutrition": (210, 8, 22, 10, 6),
        "ingredients": [("Patlıcan", 1), ("Kabak", 1), ("Patates", 2), ("Havuç", 1), ("Yeşil biber", 2), ("Domates", 3), ("Soğan", 1), ("Sarımsak", 2), ("Zeytinyağı", 3), ("Kaşar peyniri", 80), ("Tuz", 1)],
        "recipe": "1. Sebzeleri iri doğrayıp tuz ve zeytinyağıyla karıştırın.\n2. Güveç kabına alın, rendelenmiş domates ve yarım su bardağı su ekleyin.\n3. Kapağını kapatıp 190 derece fırında 40 dakika pişirin.\n4. Üzerine rendelenmiş kaşarı serpip 5 dakika daha kızartın.",
    },
    {
        "name": "Patlıcan Kebabı",
        "desc": "Kıyma ve patlıcanın biber salçalı tepsi kebabı.",
        "region": "guneydogu", "categories": ["sebze", "et"],
        "prep": 25, "cook": 35, "servings": 4, "cost": 260,
        "nutrition": (330, 18, 14, 23, 5),
        "ingredients": [("Patlıcan", 4), ("Kıyma", 300), ("Soğan", 1), ("Domates", 2), ("Yeşil biber", 2), ("Biber salçası", 1), ("Maydanoz", 0.5), ("Sıvı yağ", 3), ("Kimyon", 0.5), ("Tuz", 1)],
        "recipe": "1. Patlıcanları alaca soyup kalınca doğrayın, tuzlu suda bekletin ve kurulayın.\n2. Kıymayı rendelenmiş soğan, maydanoz, biber salçası, kimyon ve tuzla yoğurup küçük köfteler yapın.\n3. Tepsiye patlıcan ve köfteleri sırayla dizin.\n4. Aralara biber ve domates koyun, yağ ve yarım su bardağı su gezdirin.\n5. 200 derece fırında 35 dakika pişirin.",
    },
    {
        "name": "Yoğurtlu Patlıcan Kızartması",
        "desc": "Domates soslu, sarımsaklı yoğurtla servis edilen patlıcan kızartması.",
        "region": "turkiye", "categories": ["sebze"],
        "prep": 20, "cook": 25, "servings": 4, "cost": 130,
        "nutrition": (250, 7, 16, 18, 5),
        "ingredients": [("Patlıcan", 3), ("Yoğurt", 300), ("Sarımsak", 2), ("Domates", 2), ("Salça", 1), ("Sıvı yağ", 5), ("Tuz", 1)],
        "recipe": "1. Patlıcanları alaca soyup dilimleyin, tuzlu suda bekletip kurulayın ve yağda kızartın.\n2. Salçayı yağda kavurup rendelenmiş domates ve biraz su ekleyerek sos hazırlayın.\n3. Yoğurdu ezilmiş sarımsak ve tuzla karıştırın.\n4. Tabağa patlıcanları dizin, üzerine yoğurt ve domates sosu gezdirin.",
    },
    {
        "name": "Taze Bakla",
        "desc": "Dereotlu, limonlu zeytinyağlı taze bakla.",
        "region": "ege", "categories": ["sebze"],
        "prep": 20, "cook": 30, "servings": 4, "cost": 130,
        "nutrition": (190, 9, 20, 9, 8),
        "ingredients": [("Taze bakla", 700), ("Soğan", 1), ("Havuç", 1), ("Dereotu", 1), ("Zeytinyağı", 4), ("Limon", 1), ("Şeker", 5), ("Tuz", 1)],
        "recipe": "1. Baklaların uçlarını ayıklayıp iri doğrayın.\n2. Zeytinyağında soğanı ve havucu kavurun.\n3. Baklaları, şekeri, tuzu ve limon suyunu ekleyin.\n4. Yarım su bardağı su koyup 25 dakika pişirin.\n5. Soğuduktan sonra kıyılmış dereotuyla servis edin.",
    },
    {
        "name": "Lahana Sarması",
        "desc": "Kıymalı pirinç harçlı klasik lahana sarması.",
        "region": "turkiye", "categories": ["sebze", "et"],
        "prep": 50, "cook": 45, "servings": 4, "cost": 190,
        "nutrition": (280, 14, 28, 12, 4),
        "ingredients": [("Beyaz lahana", 800), ("Kıyma", 200), ("Pirinç", 80), ("Soğan", 1), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Lahananın yapraklarını haşlayıp kalın damarlarını inceltin.\n2. Kıyma, yıkanmış pirinç, rendelenmiş soğan, salça, yağ ve tuzu yoğurun.\n3. Harcı yapraklara koyup sıkıca sarın.\n4. Tencereye dizip 2 su bardağı sıcak su ekleyin ve üzerine tabak koyun.\n5. Kısık ateşte 45 dakika pişirin.",
    },
]
