MEALS = [
    {
        "name": "Tavuk Sote",
        "desc": "Biberli, domatesli hızlı tavuk sote.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 15, "cook": 25, "servings": 4, "cost": 230,
        "nutrition": (260, 32, 8, 11, 2),
        "ingredients": [("Tavuk göğsü", 500), ("Yeşil biber", 2), ("Domates", 2), ("Soğan", 1), ("Sarımsak", 1), ("Zeytinyağı", 2), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Tavuğu küp doğrayıp zeytinyağında beyazlaşana kadar kavurun.\n2. Soğanı ve sarımsağı ekleyin.\n3. Biberleri ve doğranmış domatesi ilave edin.\n4. Tuz ve karabiberle tatlandırıp suyunu çekene kadar 15 dakika pişirin.",
    },
    {
        "name": "Fırında Baharatlı Tavuk But",
        "desc": "Yoğurtlu, salçalı marineyle fırında pişen tavuk but, yanında patates.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 15, "cook": 50, "servings": 4, "cost": 260,
        "nutrition": (480, 35, 25, 26, 3),
        "ingredients": [("Tavuk but", 4), ("Yoğurt", 100), ("Salça", 1), ("Sarımsak", 3), ("Toz kırmızı biber", 1), ("Kekik", 1), ("Sıvı yağ", 2), ("Tuz", 1), ("Patates", 3)],
        "recipe": "1. Yoğurt, salça, ezilmiş sarımsak, biber, kekik, yağ ve tuzu karıştırıp marine hazırlayın.\n2. Tavuk butları marineye bulayıp en az 30 dakika bekletin.\n3. Tepsiye butları ve dilimlenmiş patatesleri yerleştirin.\n4. 200 derece fırında 50 dakika, ara ara çevirerek pişirin.",
    },
    {
        "name": "Tavuk Şiş",
        "desc": "Yoğurtlu marineyle ızgara tavuk şiş.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 20, "cook": 20, "servings": 4, "cost": 250,
        "nutrition": (290, 38, 6, 12, 1),
        "ingredients": [("Tavuk göğsü", 500), ("Yoğurt", 100), ("Sarımsak", 2), ("Salça", 1), ("Toz kırmızı biber", 1), ("Zeytinyağı", 2), ("Yeşil biber", 2), ("Domates", 2), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Tavuğu küp doğrayın.\n2. Yoğurt, ezilmiş sarımsak, salça, biber, zeytinyağı ve baharatlarla karıştırıp en az 1 saat bekletin.\n3. Şişlere dizin, aralarına biber ve domates ekleyin.\n4. Izgarada veya fırında 15-20 dakika pişirin.",
    },
    {
        "name": "Çerkez Tavuğu",
        "desc": "Cevizli, ekmekli soğuk tavuk sosu; İstanbul mezelerinden.",
        "region": "marmara", "categories": ["tavuk"],
        "prep": 30, "cook": 30, "servings": 4, "cost": 320,
        "nutrition": (410, 34, 14, 26, 2),
        "ingredients": [("Tavuk göğsü", 500), ("Ekmek", 3), ("Ceviz", 100), ("Sarımsak", 2), ("Toz kırmızı biber", 1), ("Tereyağı", 1), ("Tuz", 1)],
        "recipe": "1. Tavuğu soğan ve tuzla haşlayıp didikleyin, suyunu saklayın.\n2. Ekmek içini tavuk suyunda ıslatıp sıkın.\n3. Ceviz, sarımsak ve ekmeği robotta çekip tavuk suyuyla kremamsı bir sos yapın.\n4. Didiklenmiş tavuğun yarısını sosla karıştırıp servis tabağına yayın, kalanını üzerine koyun.\n5. Tereyağında kızdırılmış kırmızı biberi gezdirin.",
    },
    {
        "name": "Tavuklu Nohutlu Pilav",
        "desc": "Tavuk ve nohutla zenginleşen tam öğün pilav.",
        "region": "turkiye", "categories": ["tavuk", "pilav-makarna", "baklagil"],
        "prep": 15, "cook": 35, "servings": 4, "cost": 220,
        "nutrition": (480, 28, 64, 11, 4),
        "ingredients": [("Pirinç", 250), ("Tavuk göğsü", 300), ("Nohut", 100), ("Tereyağı", 2), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Nohutu ıslatıp haşlayın, tavuğu haşlayıp didikleyin (suyunu saklayın).\n2. Pirinci yıkayıp tereyağında kavurun.\n3. Nohut, tavuk ve 2,5 su bardağı tavuk suyunu ekleyin, tuz ve karabiber koyun.\n4. Suyunu çekene kadar kısık ateşte pişirip 10 dakika demlendirin.",
    },
    {
        "name": "Tavuk Güveç",
        "desc": "Sebzeli, mantarlı fırın tavuk güveç.",
        "region": "turkiye", "categories": ["tavuk", "sebze"],
        "prep": 25, "cook": 50, "servings": 4, "cost": 260,
        "nutrition": (310, 31, 20, 12, 4),
        "ingredients": [("Tavuk göğsü", 500), ("Patates", 2), ("Havuç", 1), ("Yeşil biber", 2), ("Domates", 2), ("Soğan", 1), ("Mantar", 150), ("Salça", 1), ("Sıvı yağ", 2), ("Tuz", 1)],
        "recipe": "1. Tavuğu küp doğrayıp yağda kavurun, soğan ve salçayı ekleyin.\n2. Güveç kabına tavuğu, doğranmış sebzeleri ve mantarı koyun.\n3. Tuzlayıp 1 su bardağı sıcak su ekleyin.\n4. Kapalı olarak 190 derece fırında 45 dakika pişirin.",
    },
    {
        "name": "Kremalı Mantarlı Tavuk",
        "desc": "Krema ve mantarla pişen yumuşak tavuk.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 15, "cook": 25, "servings": 4, "cost": 330,
        "nutrition": (380, 34, 8, 24, 2),
        "ingredients": [("Tavuk göğsü", 500), ("Mantar", 250), ("Krema", 200), ("Soğan", 1), ("Sarımsak", 2), ("Tereyağı", 1), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Tavuğu küp doğrayıp tereyağında kızarana kadar kavurun.\n2. Soğan ve sarımsağı ekleyin.\n3. Dilimlenmiş mantarı suyunu çekene kadar pişirin.\n4. Kremayı, tuzu ve karabiberi ekleyip 10 dakika kısık ateşte kıvam alana kadar pişirin.",
    },
    {
        "name": "Fırında Tavuk Kanat",
        "desc": "Salçalı, baharatlı çıtır fırın tavuk kanat.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 15, "cook": 40, "servings": 4, "cost": 260,
        "nutrition": (430, 34, 6, 30, 1),
        "ingredients": [("Tavuk kanat", 800), ("Salça", 1), ("Yoğurt", 100), ("Sıvı yağ", 2), ("Toz kırmızı biber", 1), ("Kekik", 1), ("Sarımsak", 2), ("Tuz", 1)],
        "recipe": "1. Salça, yoğurt, yağ, baharatlar ve ezilmiş sarımsağı karıştırın.\n2. Kanatları marineye bulayıp 30 dakika bekletin.\n3. Fırın tepsisine dizin.\n4. 200 derece fırında 40 dakika, yarıda çevirerek pişirin.",
    },
    {
        "name": "Ev Yapımı Tavuk Döner",
        "desc": "Yoğurtlu marineli tavuktan lavaşta tavuk döner.",
        "region": "turkiye", "categories": ["tavuk"],
        "prep": 20, "cook": 20, "servings": 4, "cost": 300,
        "nutrition": (480, 42, 38, 16, 3),
        "ingredients": [("Tavuk göğsü", 500), ("Yoğurt", 150), ("Salça", 1), ("Sarımsak", 2), ("Toz kırmızı biber", 1), ("Kimyon", 1), ("Sıvı yağ", 2), ("Lavaş", 4), ("Domates", 2), ("Marul", 1), ("Tuz", 1)],
        "recipe": "1. Tavuğu ince şeritler halinde kesin.\n2. Yoğurt, salça, sarımsak, biber, kimyon, yağ ve tuzla en az 1 saat marine edin.\n3. Yüksek ateşte tavada suyunu çekip kızarana kadar pişirin.\n4. Lavaşa doğranmış domates, marul ve tavuğu koyup dürüm yapın.",
    },
    {
        "name": "Hamsi Tava",
        "desc": "Mısır unuyla kızartılmış Karadeniz hamsisi.",
        "region": "karadeniz", "categories": ["balik"],
        "prep": 20, "cook": 15, "servings": 4, "cost": 260,
        "nutrition": (390, 28, 18, 22, 1),
        "ingredients": [("Hamsi", 600), ("Mısır unu", 60), ("Sıvı yağ", 6), ("Tuz", 1), ("Limon", 1)],
        "recipe": "1. Hamsileri ayıklayıp yıkayın, kafalarını çıkarıp açın ve kurulayın.\n2. Tuzlayıp mısır ununa bulayın.\n3. Kızgın yağda iki yüzünü de altın rengi olana kadar kızartın.\n4. Limon ve roka salatasıyla sıcak servis edin.",
    },
    {
        "name": "Hamsi Buğulama",
        "desc": "Domates ve biberle tencerede buğulanmış hamsi.",
        "region": "karadeniz", "categories": ["balik"],
        "prep": 20, "cook": 20, "servings": 4, "cost": 270,
        "nutrition": (280, 28, 6, 16, 1),
        "ingredients": [("Hamsi", 600), ("Soğan", 1), ("Domates", 2), ("Yeşil biber", 2), ("Maydanoz", 1), ("Zeytinyağı", 3), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Tencerenin tabanına halka soğan, domates ve biber dilimlerini dizin.\n2. Temizlenmiş hamsileri üzerine sıralayın, tuzlayın.\n3. Zeytinyağı ve yarım su bardağı su gezdirin.\n4. Kapağını kapatıp kısık ateşte 15-20 dakika buğulayın.\n5. Maydanoz ve limonla servis edin.",
    },
    {
        "name": "Hamsili Pilav",
        "desc": "Kuş üzümlü, tarçınlı klasik Karadeniz hamsili pilavı.",
        "region": "karadeniz", "categories": ["balik", "pilav-makarna"],
        "prep": 30, "cook": 50, "servings": 4, "cost": 250,
        "nutrition": (520, 28, 64, 16, 2),
        "ingredients": [("Hamsi", 400), ("Pirinç", 250), ("Soğan", 2), ("Kuş üzümü", 20), ("Çam fıstığı", 20), ("Tereyağı", 1), ("Zeytinyağı", 2), ("Tarçın", 0.5), ("Yenibahar", 0.5), ("Dereotu", 1), ("Tuz", 1)],
        "recipe": "1. Hamsileri temizleyip kılçıklarını ayırın.\n2. Yağda soğanı ve çam fıstığını kavurun, yıkanmış pirinci, kuş üzümünü ve baharatları ekleyip çevirin.\n3. Sıcak su ve tuz ilave edip pirinci yarı pişirin.\n4. Tencereye önce yarım pilavı, ardından hamsileri, sonra kalan pilavı yerleştirin.\n5. Kısık ateşte 20 dakika demleyip ters çevirerek servis edin.",
    },
    {
        "name": "Fırında Levrek",
        "desc": "Sebzeli, limonlu fırın levrek.",
        "region": "ege", "categories": ["balik"],
        "prep": 15, "cook": 30, "servings": 4, "cost": 700,
        "nutrition": (360, 38, 7, 20, 2),
        "ingredients": [("Levrek", 2), ("Limon", 1), ("Zeytinyağı", 3), ("Domates", 2), ("Yeşil biber", 2), ("Soğan", 1), ("Maydanoz", 0.5), ("Tuz", 1)],
        "recipe": "1. Levrekleri temizleyip tuzlayın, karınlarına limon dilimi ve maydanoz koyun.\n2. Tepsiye halka soğan, domates ve biberi dizin.\n3. Balıkları üzerine yerleştirip zeytinyağı gezdirin.\n4. 200 derece fırında 25-30 dakika pişirin.",
    },
    {
        "name": "Izgara Çipura",
        "desc": "Sade, zeytinyağlı ızgara çipura.",
        "region": "ege", "categories": ["balik"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 700,
        "nutrition": (330, 36, 1, 20, 0),
        "ingredients": [("Çipura", 2), ("Limon", 1), ("Zeytinyağı", 2), ("Tuz", 1), ("Roka", 1), ("Kekik", 0.5)],
        "recipe": "1. Çipuraları temizleyip her iki yüzüne çentik atın.\n2. Tuz, zeytinyağı ve kekikle ovun.\n3. Izgarada her yüzünü 8-10 dakika pişirin.\n4. Roka ve limonla servis edin.",
    },
    {
        "name": "Fırında Somon",
        "desc": "Limonlu, sarımsaklı fırın somon.",
        "region": "turkiye", "categories": ["balik"],
        "prep": 10, "cook": 20, "servings": 4, "cost": 620,
        "nutrition": (330, 32, 1, 22, 0),
        "ingredients": [("Somon", 500), ("Limon", 1), ("Zeytinyağı", 2), ("Sarımsak", 2), ("Dereotu", 0.5), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Somonu tuz, karabiber, ezilmiş sarımsak ve zeytinyağıyla ovun.\n2. Üzerine limon dilimleri ve dereotu koyun.\n3. 200 derece fırında 18-20 dakika pişirin.\n4. Salata ile servis edin.",
    },
    {
        "name": "Mezgit Tava",
        "desc": "Mısır unlu, çıtır mezgit tava.",
        "region": "karadeniz", "categories": ["balik"],
        "prep": 15, "cook": 15, "servings": 4, "cost": 300,
        "nutrition": (350, 30, 14, 18, 1),
        "ingredients": [("Mezgit", 600), ("Mısır unu", 60), ("Sıvı yağ", 6), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Mezgitleri temizleyip tuzlayın.\n2. Mısır ununa bulayın.\n3. Kızgın yağda iki yüzünü de 4-5 dakika kızartın.\n4. Limonla servis edin.",
    },
    {
        "name": "Kalamar Tava",
        "desc": "Unlanıp kızartılmış çıtır kalamar.",
        "region": "ege", "categories": ["balik"],
        "prep": 20, "cook": 10, "servings": 4, "cost": 420,
        "nutrition": (380, 26, 26, 19, 1),
        "ingredients": [("Kalamar", 500), ("Un", 80), ("Sıvı yağ", 6), ("Limon", 1), ("Tuz", 1), ("Karabiber", 0.5)],
        "recipe": "1. Kalamarları halka doğrayıp tuz ve karabiberle harmanlayın.\n2. Una bulayıp fazlasını silkeleyin.\n3. Kızgın yağda 2-3 dakika kızartın.\n4. Limon ve tarator sosla servis edin.",
    },
    {
        "name": "Karides Güveç",
        "desc": "Tereyağlı, kaşarlı, fırında pişen karides güveç.",
        "region": "ege", "categories": ["balik"],
        "prep": 20, "cook": 15, "servings": 4, "cost": 520,
        "nutrition": (330, 30, 8, 20, 1),
        "ingredients": [("Karides", 400), ("Domates", 2), ("Sarımsak", 3), ("Tereyağı", 2), ("Yeşil biber", 2), ("Kaşar peyniri", 100), ("Tuz", 1), ("Pul biber", 1)],
        "recipe": "1. Tereyağında sarımsağı ve biberi kavurun.\n2. Doğranmış domatesi ekleyip 5 dakika pişirin.\n3. Karidesleri ve baharatları katıp güveç kaplarına paylaştırın.\n4. Üzerine rendelenmiş kaşar serpin.\n5. 220 derece fırında 10 dakika, peynir eriyip kızarana kadar pişirin.",
    },
    {
        "name": "Sardalya Tava",
        "desc": "Unlu, çıtır sardalya tava.",
        "region": "ege", "categories": ["balik"],
        "prep": 15, "cook": 10, "servings": 4, "cost": 300,
        "nutrition": (350, 32, 9, 21, 0),
        "ingredients": [("Sardalya", 600), ("Un", 40), ("Sıvı yağ", 5), ("Limon", 1), ("Tuz", 1)],
        "recipe": "1. Sardalyaları temizleyip tuzlayın.\n2. Una bulayıp fazlasını silkeleyin.\n3. Kızgın yağda iki yüzünü de 3-4 dakika kızartın.\n4. Limonla servis edin.",
    },
]
